# Generated by Django 5.1.6 on 2025-02-24 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_label', models.CharField(max_length=255, null=True)),
                ('name_first', models.CharField(max_length=255, null=True)),
                ('name_last', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_label', models.CharField(max_length=255, null=True)),
                ('acronym', models.CharField(max_length=255, null=True)),
                ('person_architect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_architect', to='core.person')),
                ('person_developers', models.ManyToManyField(to='core.person')),
                ('person_lead_developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_lead_developer', to='core.person')),
                ('person_product_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_product_manager', to='core.person')),
                ('person_product_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_product_owner', to='core.person')),
                ('person_project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_project_manager', to='core.person')),
                ('person_scrum_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_scrum_master', to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
