# Generated by Django 5.1.6 on 2025-02-25 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='person_architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_architect', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_developers',
            field=models.ManyToManyField(blank=True, to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_lead_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_lead_developer', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_product_manager', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_product_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_product_owner', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_project_manager', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_scrum_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications_as_scrum_master', to='core.person'),
        ),
    ]
