# Generated by Django 5.1.7 on 2026-01-11 22:30
#
# IMPORTANT: This migration cleans up Historical model classes after 0002 dropped the tables.
# The tables no longer exist (dropped by 0002_drop_unused_historical_tables),
# so this migration should be FAKE-APPLIED on all systems:
#
#   python manage.py migrate --fake core 0003
#
# This migration exists to keep Django's migration state consistent with the code.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drop_unused_historical_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalapplicationpin',
            name='application',
        ),
        migrations.RemoveField(
            model_name='historicalapplicationpin',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalapplicationpin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaldatabasesizehistory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpasskeychallenge',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpasskeychallenge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaluserbookmark',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='historicaluserbookmark',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluserbookmark',
            name='link',
        ),
        migrations.RemoveField(
            model_name='historicaluserbookmark',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalAPIRequestExecution',
        ),
        migrations.DeleteModel(
            name='HistoricalApplicationPin',
        ),
        migrations.DeleteModel(
            name='HistoricalDatabaseSizeHistory',
        ),
        migrations.DeleteModel(
            name='HistoricalPasskeyChallenge',
        ),
        migrations.DeleteModel(
            name='HistoricalUserBookmark',
        ),
    ]
