# Generated by Django 5.1.7 on 2026-01-12 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_acronym_enumeration_attack_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='user_of_last_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_last_run', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aigovernance',
            name='ai_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_governance_records', to='core.aivendor'),
        ),
        migrations.AlterField(
            model_name='aigovernance',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_governance', to='core.application'),
        ),
        migrations.AlterField(
            model_name='aigovernance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_governance_approvals', to='core.person'),
        ),
        migrations.AlterField(
            model_name='aigovernance',
            name='data_used_for_training',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aigovernance',
            name='risk_assessment_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aigovernance',
            name='supporting_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_governance_supporting', to='core.document'),
        ),
        migrations.AlterField(
            model_name='aihallucination',
            name='ai_use_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallucinations', to='core.aiusecase'),
        ),
        migrations.AlterField(
            model_name='aihallucination',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_hallucinations_reported', to='core.person'),
        ),
        migrations.AlterField(
            model_name='aihallucination',
            name='supporting_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_hallucination_documentation', to='core.document'),
        ),
        migrations.AlterField(
            model_name='aiusecase',
            name='ai_governance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_cases', to='core.aigovernance'),
        ),
        migrations.AlterField(
            model_name='aiusecase',
            name='applications_involved',
            field=models.ManyToManyField(blank=True, related_name='ai_use_cases', to='core.application'),
        ),
        migrations.AlterField(
            model_name='aiusecase',
            name='data_used_for_ai_training',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiusecase',
            name='databases_involved',
            field=models.ManyToManyField(blank=True, related_name='ai_use_cases', to='core.database'),
        ),
        migrations.AlterField(
            model_name='aiusecase',
            name='encryption_used',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiusecase',
            name='human_oversight_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiusecase',
            name='personal_data_involved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiusecase',
            name='tools_involved',
            field=models.ManyToManyField(blank=True, related_name='ai_use_cases', to='core.tool'),
        ),
        migrations.AlterField(
            model_name='aiusecase',
            name='training_data_opt_out_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='core.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='api',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apis', to='core.tool'),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authentications', to='core.api'),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='secret_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_auth_api_key', to='core.secret'),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='secret_basic_auth_password',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_auth_basic_password', to='core.secret'),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='secret_bearer_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_auth_bearer_token', to='core.secret'),
        ),
        migrations.AlterField(
            model_name='apiauthentication',
            name='secret_oauth_client_secret',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_auth_oauth_secret', to='core.secret'),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.api'),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='authentication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.apiauthentication'),
        ),
        migrations.AlterField(
            model_name='apirequestexecution',
            name='api_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='core.apirequest'),
        ),
        migrations.AlterField(
            model_name='apirequestexecution',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_executions', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_downstream_dependencies',
            field=models.ManyToManyField(blank=True, related_name='upstream_dependent_applications', to='core.application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_group_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.applicationgroup'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_groups',
            field=models.ManyToManyField(blank=True, related_name='grouped_applications', to='core.applicationgroup'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_upstream_dependencies',
            field=models.ManyToManyField(blank=True, related_name='downstream_dependent_applications', to='core.application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_externally_facing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_legacy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_required_to_adhere_to_california_consumer_privacy_act_ccpa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_required_to_adhere_to_general_data_protection_regulation_gdpr',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_required_to_adhere_to_payment_card_industry_data_security_standard_pci_dss',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_storing_nonpublic_personal_information_npi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_storing_personally_identifiable_information_pii',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_storing_protected_health_information_phi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_using_artificial_intelligence',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_as_architect', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_lead_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_as_lead_developer', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_product_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_as_product_manager', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_product_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_as_product_owner', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_as_project_manager', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_scrum_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_as_scrum_master', to='core.person'),
        ),
        migrations.AlterField(
            model_name='applicationgroup',
            name='is_externally_facing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationgroup',
            name='is_platform',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationpin',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='core.application'),
        ),
        migrations.AlterField(
            model_name='applicationpin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='badinteraction',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_interactions', to='core.person'),
        ),
        migrations.AlterField(
            model_name='badinteraction',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_bad_interactions', to='core.person'),
        ),
        migrations.AlterField(
            model_name='badinteractionupdate',
            name='bad_interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='core.badinteraction'),
        ),
        migrations.AlterField(
            model_name='badinteractionupdate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bad_interaction_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingcode',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_codes', to='core.application'),
        ),
        migrations.AlterField(
            model_name='billingcode',
            name='application_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_codes', to='core.applicationgroup'),
        ),
        migrations.AlterField(
            model_name='billingcode',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_codes_managed', to='core.person'),
        ),
        migrations.AlterField(
            model_name='billingcode',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by_codes', to='core.billingcode'),
        ),
        migrations.AlterField(
            model_name='billingcode',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_codes', to='core.team'),
        ),
        migrations.AlterField(
            model_name='bookmarkfolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_folders', to='core.bookmarkfolder'),
        ),
        migrations.AlterField(
            model_name='bookmarkfolder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmark_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='database',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='databases', to='core.application'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='dependencies', to='core.application'),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='is_heavy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations', to='core.application'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='contingency_padding_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimations', to='core.project'),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='code_review_hours_junior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='code_review_hours_lead',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='code_review_hours_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='code_review_hours_senior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='code_reviewer_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.estimation'),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='hours_junior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='hours_lead',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='hours_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='hours_senior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='story_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='tests_hours_junior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='tests_hours_lead',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='tests_hours_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='estimationitem',
            name='tests_hours_senior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='externalblockers',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_blockers', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='gitlabiteration',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_lab_iterations', to='core.sprint'),
        ),
        migrations.AlterField(
            model_name='historicalaigovernance',
            name='data_used_for_training',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaigovernance',
            name='risk_assessment_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaiusecase',
            name='data_used_for_ai_training',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaiusecase',
            name='encryption_used',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaiusecase',
            name='human_oversight_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaiusecase',
            name='personal_data_involved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaiusecase',
            name='training_data_opt_out_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_externally_facing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_legacy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_required_to_adhere_to_california_consumer_privacy_act_ccpa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_required_to_adhere_to_general_data_protection_regulation_gdpr',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_required_to_adhere_to_payment_card_industry_data_security_standard_pci_dss',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_storing_nonpublic_personal_information_npi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_storing_personally_identifiable_information_pii',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_storing_protected_health_information_phi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='is_using_artificial_intelligence',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplicationgroup',
            name='is_externally_facing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplicationgroup',
            name='is_platform',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldependency',
            name='is_heavy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimation',
            name='contingency_padding_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='code_review_hours_junior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='code_review_hours_lead',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='code_review_hours_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='code_review_hours_senior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='code_reviewer_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='hours_junior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='hours_lead',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='hours_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='hours_senior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='story_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='tests_hours_junior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='tests_hours_lead',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='tests_hours_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalestimationitem',
            name='tests_hours_senior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='gitlab_sync_is_locked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='is_bot',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequirement',
            name='is_for_soc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequirement',
            name='is_for_spsrd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrequirement',
            name='is_functional_requirement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsprint',
            name='cached_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsprint',
            name='cached_velocity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalthisserverconfiguration',
            name='scrum_capacity_base_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hrincident',
            name='filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_hr_incidents', to='core.person'),
        ),
        migrations.AlterField(
            model_name='hrincident',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_incidents', to='core.person'),
        ),
        migrations.AlterField(
            model_name='hrincidentupdate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_incident_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hrincidentupdate',
            name='hr_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='core.hrincident'),
        ),
        migrations.AlterField(
            model_name='itdevopsrequest',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_devops_requests', to='core.application'),
        ),
        migrations.AlterField(
            model_name='itdevopsrequest',
            name='person_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_devops_requests_approved', to='core.person'),
        ),
        migrations.AlterField(
            model_name='itdevopsrequest',
            name='person_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_devops_requests_assigned', to='core.person'),
        ),
        migrations.AlterField(
            model_name='itdevopsrequest',
            name='person_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_devops_requests_requested', to='core.person'),
        ),
        migrations.AlterField(
            model_name='itdevopsrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_devops_requests', to='core.project'),
        ),
        migrations.AlterField(
            model_name='itdevopsrequestupdate',
            name='it_devops_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='core.itdevopsrequest'),
        ),
        migrations.AlterField(
            model_name='itdevopsrequestupdate',
            name='person_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_devops_request_updates_authored', to='core.person'),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_credentials_application', to='core.application'),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_credentials_database', to='core.database'),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_credentials_person', to='core.person'),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_credentials', to='core.server'),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_credentials_service_provider', to='core.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='logincredential',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_credentials_tool', to='core.tool'),
        ),
        migrations.AlterField(
            model_name='maintenancewindow',
            name='person_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_windows_as_contact', to='core.person'),
        ),
        migrations.AlterField(
            model_name='maintenancewindow',
            name='person_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_windows_created', to='core.person'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='core.application'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_organized', to='core.person'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='core.project'),
        ),
        migrations.AlterField(
            model_name='meetingactionitem',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items_assigned', to='core.person'),
        ),
        migrations.AlterField(
            model_name='meetingactionitem',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_items', to='core.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.meeting'),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_notes', to='core.person'),
        ),
        migrations.AlterField(
            model_name='onboardprocedure',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='core.tool'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gitlab_sync_is_locked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_bot',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='core.joblevel'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='core.jobtitle'),
        ),
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='core.role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='core.skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='core.application'),
        ),
        migrations.AlterField(
            model_name='project',
            name='person_stake_holders',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='core.person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_managed', to='core.person'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='core.application'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='estimation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='core.estimation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='person_recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations_made', to='core.person'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='core.project'),
        ),
        migrations.AlterField(
            model_name='release',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='core.application'),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='core.releasebundle'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='core.application'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_for_soc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_for_spsrd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='is_functional_requirement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovidersecurityrequirementsdocument',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='core.application'),
        ),
        migrations.AlterField(
            model_name='serviceprovidersecurityrequirementsdocument',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='core.client'),
        ),
        migrations.AlterField(
            model_name='serviceprovidersecurityrequirementsdocument',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='core.requirement'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='cached_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='cached_velocity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='thisserverconfiguration',
            name='connection_chatgpt_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_config_chatgpt', to='core.secret'),
        ),
        migrations.AlterField(
            model_name='thisserverconfiguration',
            name='connection_git_lab_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='core.secret'),
        ),
        migrations.AlterField(
            model_name='thisserverconfiguration',
            name='connection_google_maps_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_config_google_maps', to='core.secret'),
        ),
        migrations.AlterField(
            model_name='thisserverconfiguration',
            name='kpi_developers_to_exclude',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_set', to='core.person'),
        ),
        migrations.AlterField(
            model_name='thisserverconfiguration',
            name='scrum_capacity_base_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='thisserverconfiguration',
            name='type_developer_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='core.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_mapping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='core.person'),
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='core.bookmarkfolder'),
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bookmarks', to='core.link'),
        ),
        migrations.AlterField(
            model_name='userbookmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpasskey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passkeys', to=settings.AUTH_USER_MODEL),
        ),
    ]
