# Generated by Django 5.1.6 on 2025-02-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_person_job_level_person_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='link_gitlab_username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
