# Generated by Django 5.1.6 on 2025-02-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_link_gitlab_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='type_platform',
            field=models.CharField(blank=True, choices=[('Background Task', 'Background Task'), ('Chrome Plugin', 'Chrome Plugin'), ('IOS', 'IOS'), ('Microsoft Excel', 'Microsoft Excel'), ('Microsoft Excel + Visual Basic for Applications', 'Microsoft Excel + Visual Basic for Applications'), ('Microsoft Word', 'Microsoft Word'), ('WEB', 'WEB')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_level',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Mid-Level', 'Mid-Level'), ('Senior', 'Senior')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Lead Developer', 'Lead Developer'), ('Lead Software Architect', 'Lead Software Architect'), ('Product Manager', 'Product Manager'), ('Product Owner', 'Product Owner'), ('Project Manager', 'Project Manager'), ('Scrum Master', 'Scrum Master'), ('Software Architect', 'Software Architect')], max_length=25, null=True),
        ),
    ]
