# Generated by Django 5.1.7 on 2026-01-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_database_flavors'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='certificate',
            field=models.ForeignKey(blank=True, help_text='SSL/TLS certificate file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='databases_using_certificate', to='core.document'),
        ),
        migrations.AddField(
            model_name='database',
            name='encrypted_ssh_tunnel_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='encrypted_ssh_tunnel_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='is_certificate_required',
            field=models.BooleanField(blank=True, default=False, help_text='Does this connection require an SSL/TLS certificate?', null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='is_public_facing',
            field=models.BooleanField(blank=True, default=False, help_text='Is this database accessible from the public internet?', null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='is_read_only',
            field=models.BooleanField(blank=True, default=False, help_text='Is this database connection read-only?', null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='is_ssh_tunnel_required',
            field=models.BooleanField(blank=True, default=False, help_text='Does this database require SSH tunneling?', null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='ssh_tunnel_host',
            field=models.CharField(blank=True, help_text='SSH tunnel hostname', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='ssh_tunnel_port',
            field=models.IntegerField(blank=True, help_text='SSH tunnel port (usually 22)', null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='type_authentication_method',
            field=models.CharField(blank=True, choices=[('API Key', 'API Key'), ('Certificate (SSL/TLS)', 'Certificate (SSL/TLS)'), ('HMAC', 'HMAC'), ('IAM (AWS)', 'IAM (AWS)'), ('JWT Token', 'JWT Token'), ('Kerberos', 'Kerberos'), ('LDAP', 'LDAP'), ('No Authentication', 'No Authentication'), ('OAuth', 'OAuth'), ('Service Principal (Azure)', 'Service Principal (Azure)'), ('Username & Password', 'Username & Password')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='type_connection_type',
            field=models.CharField(blank=True, choices=[('Default (TCP/IP)', 'Default (TCP/IP)'), ('HTTP/HTTPS', 'HTTP/HTTPS'), ('In-Memory', 'In-Memory'), ('Named Pipe', 'Named Pipe'), ('Unix Socket', 'Unix Socket')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='type_ssl_support',
            field=models.CharField(blank=True, choices=[('Not Supported', 'Not Supported'), ('Optional', 'Optional'), ('Preferred', 'Preferred'), ('Required', 'Required')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='certificate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='SSL/TLS certificate file', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.document'),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='encrypted_ssh_tunnel_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='encrypted_ssh_tunnel_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='is_certificate_required',
            field=models.BooleanField(blank=True, default=False, help_text='Does this connection require an SSL/TLS certificate?', null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='is_public_facing',
            field=models.BooleanField(blank=True, default=False, help_text='Is this database accessible from the public internet?', null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='is_read_only',
            field=models.BooleanField(blank=True, default=False, help_text='Is this database connection read-only?', null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='is_ssh_tunnel_required',
            field=models.BooleanField(blank=True, default=False, help_text='Does this database require SSH tunneling?', null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='ssh_tunnel_host',
            field=models.CharField(blank=True, help_text='SSH tunnel hostname', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='ssh_tunnel_port',
            field=models.IntegerField(blank=True, help_text='SSH tunnel port (usually 22)', null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='type_authentication_method',
            field=models.CharField(blank=True, choices=[('API Key', 'API Key'), ('Certificate (SSL/TLS)', 'Certificate (SSL/TLS)'), ('HMAC', 'HMAC'), ('IAM (AWS)', 'IAM (AWS)'), ('JWT Token', 'JWT Token'), ('Kerberos', 'Kerberos'), ('LDAP', 'LDAP'), ('No Authentication', 'No Authentication'), ('OAuth', 'OAuth'), ('Service Principal (Azure)', 'Service Principal (Azure)'), ('Username & Password', 'Username & Password')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='type_connection_type',
            field=models.CharField(blank=True, choices=[('Default (TCP/IP)', 'Default (TCP/IP)'), ('HTTP/HTTPS', 'HTTP/HTTPS'), ('In-Memory', 'In-Memory'), ('Named Pipe', 'Named Pipe'), ('Unix Socket', 'Unix Socket')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='type_ssl_support',
            field=models.CharField(blank=True, choices=[('Not Supported', 'Not Supported'), ('Optional', 'Optional'), ('Preferred', 'Preferred'), ('Required', 'Required')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='default_environment',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Local', 'Local'), ('Local Docker', 'Local Docker'), ('Local Docker Compose', 'Local Docker Compose'), ('Production', 'Production'), ('Production External', 'Production External'), ('Staging', 'Staging')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='type_environment',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Local', 'Local'), ('Local Docker', 'Local Docker'), ('Local Docker Compose', 'Local Docker Compose'), ('Production', 'Production'), ('Production External', 'Production External'), ('Staging', 'Staging')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapirequest',
            name='default_environment',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Local', 'Local'), ('Local Docker', 'Local Docker'), ('Local Docker Compose', 'Local Docker Compose'), ('Production', 'Production'), ('Production External', 'Production External'), ('Staging', 'Staging')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldatabase',
            name='type_environment',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Local', 'Local'), ('Local Docker', 'Local Docker'), ('Local Docker Compose', 'Local Docker Compose'), ('Production', 'Production'), ('Production External', 'Production External'), ('Staging', 'Staging')], max_length=255, null=True),
        ),
    ]
