# Generated by Django 5.1.6 on 2025-02-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_acronym_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='connection_gitlab_api_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='connection_gitlab_group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='connection_gitlab_api_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='connection_gitlab_group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
