# Generated by Django 5.1.6 on 2025-02-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_type_platform_alter_person_job_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_downstream_dependencies',
            field=models.ManyToManyField(blank=True, to='core.application'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_upstream_dependencies',
            field=models.ManyToManyField(blank=True, to='core.application'),
        ),
        migrations.AddField(
            model_name='application',
            name='date_launch',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_externally_facing',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='link_development_server',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='link_gitlab_repository',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='link_production_server',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='link_production_server_external',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='link_staging_server',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='peak_userbase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='type_authentication',
            field=models.CharField(blank=True, choices=[('Active Directory (AD)', 'Active Directory (AD)'), ('Custom', 'Custom')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='type_authorization',
            field=models.CharField(blank=True, choices=[('Active Directory (AD)', 'Active Directory (AD)'), ('Custom', 'Custom')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='type_deployment_medium',
            field=models.CharField(blank=True, choices=[('Cloud - Azure Kubernetes Service (AKS)', 'Cloud - Azure Kubernetes Service (AKS)'), ('Cloud - Divio', 'Cloud - Divio'), ('On-Premises - Windows Internet Information Services (IIS)', 'On-Premises - Windows Internet Information Services (IIS)'), ('On-Premises - Debian Linux', 'On-Premises - Debian Linux')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='type_lifecycle',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Awaiting Approval', 'Awaiting Approval'), ('Deprecated', 'Deprecated'), ('In Development', 'In Development'), ('Hyper Care', 'Hyper Care'), ('Idea Submission', 'Idea Submission'), ('In Deprecation Period', 'In Deprecation Period'), ('Limited Support', 'Limited Support'), ('In Planning', 'In Planning'), ('Approval Rejected', 'Approval Rejected')], max_length=255, null=True),
        ),
    ]
