# Generated by Django 5.1.7 on 2026-01-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicalproposal_proposal_historicalproposalupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='service_providers', to='core.tool'),
        ),
    ]
