# Generated by Django 5.1.6 on 2025-02-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_application_acronym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Lead Developer', 'Lead Developer'), ('Lead Software Architect', 'Lead Software Architect'), ('Manager', 'Manager'), ('Product Manager', 'Product Manager'), ('Product Owner', 'Product Owner'), ('Project Manager', 'Project Manager'), ('Scrum Master', 'Scrum Master'), ('Software Architect', 'Software Architect')], max_length=25, null=True),
        ),
    ]
