# Generated by Django 5.1.6 on 2025-03-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_action_historicalaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalperson',
            old_name='link_gitlab_username',
            new_name='gitlab_sync_username',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='link_gitlab_username',
            new_name='gitlab_sync_username',
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gitlab_sync_access_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gitlab_sync_avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gitlab_sync_datetime_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gitlab_sync_datetime_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gitlab_sync_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gitlab_sync_is_locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gitlab_sync_membership_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gitlab_sync_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gitlab_sync_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='gitlab_sync_web_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gitlab_sync_access_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gitlab_sync_avatar_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gitlab_sync_datetime_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gitlab_sync_datetime_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gitlab_sync_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gitlab_sync_is_locked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gitlab_sync_membership_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gitlab_sync_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gitlab_sync_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gitlab_sync_web_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
