# Generated by Django 5.1.7 on 2026-01-26 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_serviceprovider_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='acronym',
            name='term',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acronym', to='core.term'),
        ),
        migrations.AddField(
            model_name='historicalacronym',
            name='term',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.term'),
        ),
    ]
