# Generated by Django 5.1.7 on 2026-01-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_acronym_term_historicalacronym_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaldatabase',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
