# Generated by Django 5.1.6 on 2025-03-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_command_historicalcommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='is_bot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_bot',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
