# Generated by Django 5.1.6 on 2025-02-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_releasebundle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasebundle',
            name='date_code_freeze',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releasebundle',
            name='date_demo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releasebundle',
            name='date_release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('type_dependency', models.CharField(blank=True, choices=[('Framework', 'Framework'), ('Language', 'Language'), ('Package', 'Package'), ('Protocol', 'Protocol'), ('Standard', 'Standard')], max_length=255, null=True)),
                ('applications', models.ManyToManyField(blank=True, to='core.application')),
            ],
        ),
    ]
