# Generated by Django 5.1.7 on 2026-01-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_name_field_to_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='badinteraction',
            name='name',
            field=models.CharField(blank=True, help_text='Brief title for the interaction', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalbadinteraction',
            name='name',
            field=models.CharField(blank=True, help_text='Brief title for the interaction', max_length=255, null=True),
        ),
    ]
