# Generated by Django 5.1.7 on 2026-01-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_name_to_bad_interaction'),
    ]

    operations = [
        # Add evidence_document FK to BadInteraction
        migrations.AddField(
            model_name='badinteraction',
            name='evidence_document',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='evidence_for_bad_interactions',
                to='core.document',
            ),
        ),
        migrations.AddField(
            model_name='historicalbadinteraction',
            name='evidence_document',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='core.document',
            ),
        ),
        # Add attachment_document FK to BadInteractionUpdate
        migrations.AddField(
            model_name='badinteractionupdate',
            name='attachment_document',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attachment_for_bad_interaction_updates',
                to='core.document',
            ),
        ),
        migrations.AddField(
            model_name='historicalbadinteractionupdate',
            name='attachment_document',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='core.document',
            ),
        ),
        # Add attachment_document FK to HRIncidentUpdate
        migrations.AddField(
            model_name='hrincidentupdate',
            name='attachment_document',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attachment_for_hr_incident_updates',
                to='core.document',
            ),
        ),
        migrations.AddField(
            model_name='historicalhrincidentupdate',
            name='attachment_document',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='core.document',
            ),
        ),
    ]
