# Generated by Django 5.1.7 on 2026-01-28

from django.db import migrations


def migrate_files_to_documents(apps, schema_editor):
    """
    Migrate existing FileField data to Document ForeignKey relationships.
    Creates new Document instances for each existing file reference.
    """
    Document = apps.get_model('core', 'Document')
    BadInteraction = apps.get_model('core', 'BadInteraction')
    BadInteractionUpdate = apps.get_model('core', 'BadInteractionUpdate')
    HRIncidentUpdate = apps.get_model('core', 'HRIncidentUpdate')

    # Migrate BadInteraction.evidence_file -> evidence_document
    for bad_interaction in BadInteraction.objects.filter(evidence_file__isnull=False).exclude(evidence_file=''):
        filename = bad_interaction.evidence_file.name.split('/')[-1] if bad_interaction.evidence_file else 'Evidence'
        document = Document.objects.create(
            name=filename,
            version='1.0',
        )
        # Set the file reference (same MinIO path, no copying)
        document.file.name = bad_interaction.evidence_file.name
        document.save()
        bad_interaction.evidence_document = document
        bad_interaction.save()

    # Migrate BadInteractionUpdate.attachment_file -> attachment_document
    for update in BadInteractionUpdate.objects.filter(attachment_file__isnull=False).exclude(attachment_file=''):
        filename = update.attachment_file.name.split('/')[-1] if update.attachment_file else 'Attachment'
        document = Document.objects.create(
            name=filename,
            version='1.0',
        )
        document.file.name = update.attachment_file.name
        document.save()
        update.attachment_document = document
        update.save()

    # Migrate HRIncidentUpdate.attachment_file -> attachment_document
    for update in HRIncidentUpdate.objects.filter(attachment_file__isnull=False).exclude(attachment_file=''):
        filename = update.attachment_file.name.split('/')[-1] if update.attachment_file else 'Attachment'
        document = Document.objects.create(
            name=filename,
            version='1.0',
        )
        document.file.name = update.attachment_file.name
        document.save()
        update.attachment_document = document
        update.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse: Clear the document FK fields (files remain in old fields).
    """
    BadInteraction = apps.get_model('core', 'BadInteraction')
    BadInteractionUpdate = apps.get_model('core', 'BadInteractionUpdate')
    HRIncidentUpdate = apps.get_model('core', 'HRIncidentUpdate')

    BadInteraction.objects.filter(evidence_document__isnull=False).update(evidence_document=None)
    BadInteractionUpdate.objects.filter(attachment_document__isnull=False).update(attachment_document=None)
    HRIncidentUpdate.objects.filter(attachment_document__isnull=False).update(attachment_document=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_document_fk_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_files_to_documents, reverse_migration),
    ]
