# Generated by Django 5.1.6 on 2025-02-25 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_application_comment_dependency_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='software_version',
            new_name='version',
        ),
        migrations.AddField(
            model_name='dependency',
            name='is_heavy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_employee',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='type_dependency',
            field=models.CharField(blank=True, choices=[('Binary', 'Binary'), ('Framework', 'Framework'), ('Language', 'Language'), ('Package', 'Package'), ('Protocol', 'Protocol'), ('Standard', 'Standard')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('type_database_flavor', models.CharField(blank=True, choices=[('MARIADB', 'MARIADB'), ('PostgreSQL', 'PostgreSQL')], max_length=255, null=True)),
                ('type_database_storage_model', models.CharField(blank=True, choices=[('Blob', 'Blob'), ('Document', 'Document'), ('Relational', 'Relational')], max_length=255, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='databases', to='core.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
