# Generated by Django 5.1.7 on 2026-01-28
# This migration removes the legacy FileField and M2M fields after data migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_migrate_files_to_documents'),
    ]

    operations = [
        # Remove legacy evidence_file from BadInteraction
        migrations.RemoveField(
            model_name='badinteraction',
            name='evidence_file',
        ),
        migrations.RemoveField(
            model_name='historicalbadinteraction',
            name='evidence_file',
        ),
        # Remove legacy documents M2M from BadInteraction
        migrations.RemoveField(
            model_name='badinteraction',
            name='documents',
        ),

        # Remove legacy attachment_file from BadInteractionUpdate
        migrations.RemoveField(
            model_name='badinteractionupdate',
            name='attachment_file',
        ),
        migrations.RemoveField(
            model_name='historicalbadinteractionupdate',
            name='attachment_file',
        ),
        # Remove legacy documents M2M from BadInteractionUpdate
        migrations.RemoveField(
            model_name='badinteractionupdate',
            name='documents',
        ),

        # Remove legacy attachment_file from HRIncidentUpdate
        migrations.RemoveField(
            model_name='hrincidentupdate',
            name='attachment_file',
        ),
        migrations.RemoveField(
            model_name='historicalhrincidentupdate',
            name='attachment_file',
        ),
        # Remove legacy documents M2M from HRIncidentUpdate
        migrations.RemoveField(
            model_name='hrincidentupdate',
            name='documents',
        ),
    ]
