# Generated by Django 5.1.6 on 2025-02-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_software_version_release_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='database_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
