# Generated by Django 5.1.6 on 2025-03-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historicalthisserverconfiguration_type_developer_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='scrum_capacity_base',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='scrum_capacity_base',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
