# Generated by Django 5.1.6 on 2025-02-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_database_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='type_database_flavor',
            field=models.CharField(blank=True, choices=[('MariaDB', 'MariaDB'), ('PostgreSQL', 'PostgreSQL')], max_length=255, null=True),
        ),
    ]
