# Generated by Django 5.1.6 on 2025-03-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalthisserverconfiguration_scrum_capacity_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyperformanceindicatorsprint',
            name='person_developer',
        ),
        migrations.RemoveField(
            model_name='keyperformanceindicatorsprint',
            name='sprint',
        ),
        migrations.DeleteModel(
            name='HistoricalKeyPerformanceIndicatorSprint',
        ),
        migrations.DeleteModel(
            name='KeyPerformanceIndicatorSprint',
        ),
    ]
