# Generated by Django 5.1.7 on 2026-01-28 18:07

import core.utilities.uuid_upload_path
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_old_file_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at', '-id']},
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the document was uploaded'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the document was uploaded'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='File stored in MinIO object storage', null=True, upload_to=core.utilities.uuid_upload_path.uuid_upload_path),
        ),
    ]
