# Generated by Django 5.1.6 on 2025-02-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_database_type_database_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='type_database_environment',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Development', 'Development'), ('Staging', 'Staging'), ('Production', 'Production')], max_length=255, null=True),
        ),
    ]
