# Generated by Django 5.1.7 on 2026-01-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_uploaded_at_to_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of file contents for duplicate detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of file contents for duplicate detection', max_length=64, null=True),
        ),
    ]
