# Generated by Django 5.1.6 on 2025-03-04 18:44

from django.db import migrations, models

def update_gitlab_api_version(apps, schema_editor):
    # noinspection PyPep8Naming
    ThisServerConfiguration = apps.get_model('core', 'ThisServerConfiguration')
    # noinspection PyPep8Naming
    HistoricalThisServerConfiguration = apps.get_model('core', 'HistoricalThisServerConfiguration')

    # Update ThisServerConfiguration model
    for config in ThisServerConfiguration.objects.all():
        if config.connection_gitlab_api_version == 'v4':
            config.connection_gitlab_api_version = '4'
        elif config.connection_gitlab_api_version == 'v5':
            config.connection_gitlab_api_version = '5'
        else:
            config.connection_gitlab_api_version = None
        config.save()

    # Update HistoricalThisServerConfiguration model
    for config in HistoricalThisServerConfiguration.objects.all():
        if config.connection_gitlab_api_version == 'v4':
            config.connection_gitlab_api_version = '4'
        elif config.connection_gitlab_api_version == 'v5':
            config.connection_gitlab_api_version = '5'
        else:
            config.connection_gitlab_api_version = None
        config.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_keyperformanceindicatorsprint_person_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalthisserverconfiguration',
            name='connection_gitlab_api_version',
            field=models.CharField(blank=True, choices=[('4', '4'), ('5', '5')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thisserverconfiguration',
            name='connection_gitlab_api_version',
            field=models.CharField(blank=True, choices=[('4', '4'), ('5', '5')], max_length=255, null=True),
        ),
        migrations.RunPython(update_gitlab_api_version),
    ]
