# Generated by Django 5.1.6 on 2025-02-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_database_type_database_environment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependency',
            options={'verbose_name_plural': 'Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
    ]
