# Generated by Django 5.1.7 on 2026-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_file_hash_to_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Perceptual hash (dhash) for similar image detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Perceptual hash (dhash) for similar image detection', max_length=64, null=True),
        ),
    ]
