# Generated by Django 5.1.7 on 2026-01-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_image_hash_to_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='AVIF thumbnail for fast preview', null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='thumbnail',
            field=models.TextField(blank=True, help_text='AVIF thumbnail for fast preview', max_length=100, null=True),
        ),
    ]
