# Generated by Django 5.1.6 on 2025-02-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_dependency_options_alter_person_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_name',
        ),
        migrations.RemoveField(
            model_name='database',
            name='database_name',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='dependency_name',
        ),
        migrations.RemoveField(
            model_name='releasebundle',
            name='bundle_name',
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dependency',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='releasebundle',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='type_database_environment',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Local', 'Local'), ('Production', 'Production'), ('Staging', 'Staging')], max_length=255, null=True),
        ),
    ]
