# Generated by Django 5.1.6 on 2025-03-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_gitlabiteration_sprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['-id']},
        ),
    ]
