# Generated by Django 5.1.6 on 2025-03-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_sprint_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='estimated_run_time_in_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaction',
            name='estimated_run_time_in_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
