# Generated by Django 5.1.7 on 2026-01-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_document_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasskey',
            name='rp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaluserpasskey',
            name='rp_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
