# Generated by Django 5.1.6 on 2025-02-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_application_application_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='job_level',
            new_name='type_job_level',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='job_title',
            new_name='type_job_title',
        ),
    ]
