# Generated by Django 5.1.6 on 2025-02-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_job_level_person_type_job_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='type_platform',
            new_name='type_platform_target',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='type_database_storage_model',
            new_name='type_data_storage_form',
        ),
        migrations.RenameField(
            model_name='database',
            old_name='type_database_environment',
            new_name='type_environment',
        ),
        migrations.RenameField(
            model_name='dependency',
            old_name='type_dependency',
            new_name='type_programing_concept',
        ),
    ]
