# Generated by Django 5.1.6 on 2025-03-05 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_action_estimated_run_time_in_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='datetime_of_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='number_of_times_run',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='user_of_last_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaction',
            name='datetime_of_last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaction',
            name='number_of_times_run',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaction',
            name='user_of_last_run',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
