# Generated by Django 5.1.7 on 2026-01-30

from django.db import migrations


def backfill_rp_id(apps, schema_editor):
    """
    Backfill existing passkeys with 'localhost' as the default rp_id.
    This assumes existing passkeys were registered on localhost.
    """
    UserPasskey = apps.get_model('core', 'UserPasskey')
    UserPasskey.objects.filter(rp_id__isnull=True).update(rp_id='localhost')


def reverse_backfill(apps, schema_editor):
    """Reverse migration - set rp_id back to null."""
    UserPasskey = apps.get_model('core', 'UserPasskey')
    UserPasskey.objects.filter(rp_id='localhost').update(rp_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_rp_id_to_userpasskey'),
    ]

    operations = [
        migrations.RunPython(backfill_rp_id, reverse_backfill),
    ]
