# Generated by Django 5.1.6 on 2025-02-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_type_platform_application_type_platform_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='releasebundle',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
