# Generated by Django 5.1.7 on 2026-02-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_backfill_passkey_rp_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itdevopsrequest',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='itdevopsrequestupdate',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='it_devops_request_updates', to='core.document'),
        ),
    ]
