# Generated by Django 5.1.6 on 2025-03-05 23:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_action_datetime_of_last_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
