# Generated by Django 5.1.7 on 2026-02-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_approval_approvalupdate_historicalapproval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='person_approver',
        ),
        migrations.RemoveField(
            model_name='historicalapproval',
            name='person_approver',
        ),
        migrations.AddField(
            model_name='approval',
            name='approvers',
            field=models.ManyToManyField(blank=True, related_name='approvals_approved', to='core.person'),
        ),
    ]
