# Generated by Django 5.1.6 on 2025-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_person_type_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='person_stakeholders',
            field=models.ManyToManyField(blank=True, related_name='applications_stakeholder_of', to='core.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='person_developers',
            field=models.ManyToManyField(blank=True, related_name='applications_developer_of', to='core.person'),
        ),
    ]
