# Generated by Django 5.1.7 on 2026-02-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_approval_person_approver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalupdate',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='proposal_updates', to='core.document'),
        ),
    ]
