# Generated by Django 5.1.6 on 2025-02-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_person_is_stakeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_developer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
