# Generated by Django 5.1.6 on 2025-03-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_person_job_level_alter_person_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='scrum_number_of_business_days_in_sprint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='scrum_number_of_business_days_in_sprint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
