# Generated by Django 5.1.6 on 2025-03-06 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_historicalthisserverconfiguration_scrum_number_of_business_days_in_sprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_mapping', to='core.person'),
        ),
    ]
