# Generated by Django 5.1.6 on 2025-02-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_person_date_birthday_person_date_hired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_architect',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_lead_developer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_product_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_product_owner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_project_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_scrum_master',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
