# Generated by Django 5.1.6 on 2025-03-06 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_user_person_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person_mapping',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_mapping', to='core.person'),
        ),
    ]
