# Generated by Django 5.1.6 on 2025-02-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_person_is_architect_person_is_lead_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='name_aliases',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
