# Generated by Django 5.1.6 on 2025-03-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_user_person_mapping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalthisserverconfiguration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical This Server Configuration', 'verbose_name_plural': 'historical These Server Configurations'},
        ),
        migrations.AlterModelOptions(
            name='thisserverconfiguration',
            options={'ordering': ['name', '-id'], 'verbose_name': 'This Server Configuration', 'verbose_name_plural': 'These Server Configurations'},
        ),
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='scrum_capacity_base_per_day',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='scrum_number_of_business_days_in_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='scrum_number_of_weeks_in_a_sprint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='scrum_capacity_base_per_day',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='scrum_number_of_business_days_in_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='scrum_number_of_weeks_in_a_sprint',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
