# Generated by Django 5.1.6 on 2025-03-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_historicalthisserverconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalacronym',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Acronym', 'verbose_name_plural': '_Historical Records for Acronym'},
        ),
        migrations.AlterModelOptions(
            name='historicalaction',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Action', 'verbose_name_plural': '_Historical Records for Action'},
        ),
        migrations.AlterModelOptions(
            name='historicalapplication',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Application', 'verbose_name_plural': '_Historical Records for Application'},
        ),
        migrations.AlterModelOptions(
            name='historicalapplicationgroup',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for ApplicationGroup', 'verbose_name_plural': '_Historical Records for ApplicationGroup'},
        ),
        migrations.AlterModelOptions(
            name='historicalclient',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Client', 'verbose_name_plural': '_Historical Records for Client'},
        ),
        migrations.AlterModelOptions(
            name='historicalcommand',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Command', 'verbose_name_plural': '_Historical Records for Command'},
        ),
        migrations.AlterModelOptions(
            name='historicalcronjob',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for CronJob', 'verbose_name_plural': '_Historical Records for CronJob'},
        ),
        migrations.AlterModelOptions(
            name='historicaldatabase',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Database', 'verbose_name_plural': '_Historical Records for Database'},
        ),
        migrations.AlterModelOptions(
            name='historicaldatapoint',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for DataPoint', 'verbose_name_plural': '_Historical Records for DataPoint'},
        ),
        migrations.AlterModelOptions(
            name='historicaldatauseexception',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for DataUseException', 'verbose_name_plural': '_Historical Records for DataUseException'},
        ),
        migrations.AlterModelOptions(
            name='historicaldependency',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Dependency', 'verbose_name_plural': '_Historical Records for Dependency'},
        ),
        migrations.AlterModelOptions(
            name='historicaldocument',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Document', 'verbose_name_plural': '_Historical Records for Document'},
        ),
        migrations.AlterModelOptions(
            name='historicalformula',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Formula', 'verbose_name_plural': '_Historical Records for Formula'},
        ),
        migrations.AlterModelOptions(
            name='historicalgitlabiteration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for GitLabIteration', 'verbose_name_plural': '_Historical Records for GitLabIteration'},
        ),
        migrations.AlterModelOptions(
            name='historicalhotfix',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Hotfix', 'verbose_name_plural': '_Historical Records for Hotfix'},
        ),
        migrations.AlterModelOptions(
            name='historicalincident',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Incident', 'verbose_name_plural': '_Historical Records for Incident'},
        ),
        migrations.AlterModelOptions(
            name='historicaljoblevel',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for JobLevel', 'verbose_name_plural': '_Historical Records for JobLevel'},
        ),
        migrations.AlterModelOptions(
            name='historicallink',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Link', 'verbose_name_plural': '_Historical Records for Link'},
        ),
        migrations.AlterModelOptions(
            name='historicalonboardprocedure',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for OnboardProcedure', 'verbose_name_plural': '_Historical Records for OnboardProcedure'},
        ),
        migrations.AlterModelOptions(
            name='historicalorganization',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Organization', 'verbose_name_plural': '_Historical Records for Organization'},
        ),
        migrations.AlterModelOptions(
            name='historicalperson',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Person', 'verbose_name_plural': '_Historical Records for Person'},
        ),
        migrations.AlterModelOptions(
            name='historicalpolicy',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Policy', 'verbose_name_plural': '_Historical Records for Policy'},
        ),
        migrations.AlterModelOptions(
            name='historicalproject',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Project', 'verbose_name_plural': '_Historical Records for Project'},
        ),
        migrations.AlterModelOptions(
            name='historicalrelease',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Release', 'verbose_name_plural': '_Historical Records for Release'},
        ),
        migrations.AlterModelOptions(
            name='historicalreleasebundle',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for ReleaseBundle', 'verbose_name_plural': '_Historical Records for ReleaseBundle'},
        ),
        migrations.AlterModelOptions(
            name='historicalreport',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Report', 'verbose_name_plural': '_Historical Records for Report'},
        ),
        migrations.AlterModelOptions(
            name='historicalrequirement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Requirement', 'verbose_name_plural': '_Historical Records for Requirement'},
        ),
        migrations.AlterModelOptions(
            name='historicalrisk',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Risk', 'verbose_name_plural': '_Historical Records for Risk'},
        ),
        migrations.AlterModelOptions(
            name='historicalrole',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Role', 'verbose_name_plural': '_Historical Records for Role'},
        ),
        migrations.AlterModelOptions(
            name='historicalsecret',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Secret', 'verbose_name_plural': '_Historical Records for Secret'},
        ),
        migrations.AlterModelOptions(
            name='historicalserver',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Server', 'verbose_name_plural': '_Historical Records for Server'},
        ),
        migrations.AlterModelOptions(
            name='historicalserviceprovider',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for ServiceProvider', 'verbose_name_plural': '_Historical Records for ServiceProvider'},
        ),
        migrations.AlterModelOptions(
            name='historicalserviceprovidersecurityrequirementsdocument',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for ServiceProviderSecurityRequirementsDocument', 'verbose_name_plural': '_Historical Records for ServiceProviderSecurityRequirementsDocument'},
        ),
        migrations.AlterModelOptions(
            name='historicalskill',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Skill', 'verbose_name_plural': '_Historical Records for Skill'},
        ),
        migrations.AlterModelOptions(
            name='historicalsoftwarebillofmaterial',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for SoftwareBillOfMaterial', 'verbose_name_plural': '_Historical Records for SoftwareBillOfMaterial'},
        ),
        migrations.AlterModelOptions(
            name='historicalsprint',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Sprint', 'verbose_name_plural': '_Historical Records for Sprint'},
        ),
        migrations.AlterModelOptions(
            name='historicaltask',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Task', 'verbose_name_plural': '_Historical Records for Task'},
        ),
        migrations.AlterModelOptions(
            name='historicalteam',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Team', 'verbose_name_plural': '_Historical Records for Team'},
        ),
        migrations.AlterModelOptions(
            name='historicalterm',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Term', 'verbose_name_plural': '_Historical Records for Term'},
        ),
        migrations.AlterModelOptions(
            name='historicalthisserverconfiguration',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for ThisServerConfiguration', 'verbose_name_plural': '_Historical Records for ThisServerConfiguration'},
        ),
        migrations.AlterModelOptions(
            name='historicaltool',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Tool', 'verbose_name_plural': '_Historical Records for Tool'},
        ),
        migrations.AlterModelOptions(
            name='historicalvulnerability',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for Vulnerability', 'verbose_name_plural': '_Historical Records for Vulnerability'},
        ),
    ]
