# Generated by Django 5.1.6 on 2025-02-25 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_application_name_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
                ('is_externally_facing', models.BooleanField(blank=True, default=False, null=True)),
                ('name_aliases', models.CharField(blank=True, max_length=255, null=True)),
                ('type_lifecycle', models.CharField(blank=True, choices=[('Active', 'Active'), ('Awaiting Approval', 'Awaiting Approval'), ('Deprecated', 'Deprecated'), ('In Development', 'In Development'), ('Hyper Care', 'Hyper Care'), ('Idea Submission', 'Idea Submission'), ('In Deprecation Period', 'In Deprecation Period'), ('Limited Support', 'Limited Support'), ('In Planning', 'In Planning'), ('Approval Rejected', 'Approval Rejected')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='application_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applications', to='core.applicationgroup'),
        ),
    ]
