# Generated by Django 5.1.6 on 2025-03-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_sprint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thisserverconfiguration',
            options={'ordering': ['-id'], 'verbose_name': 'This Server Configuration', 'verbose_name_plural': 'These Server Configurations'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='historicalthisserverconfiguration',
            old_name='connection_gitlab_api_version',
            new_name='connection_git_lab_api_version',
        ),
        migrations.RenameField(
            model_name='historicalthisserverconfiguration',
            old_name='connection_gitlab_group_id',
            new_name='connection_git_lab_group_id',
        ),
        migrations.RenameField(
            model_name='historicalthisserverconfiguration',
            old_name='connection_gitlab_hostname',
            new_name='connection_git_lab_hostname',
        ),
        migrations.RenameField(
            model_name='historicalthisserverconfiguration',
            old_name='connection_gitlab_token',
            new_name='connection_git_lab_token',
        ),
        migrations.RenameField(
            model_name='thisserverconfiguration',
            old_name='connection_gitlab_api_version',
            new_name='connection_git_lab_api_version',
        ),
        migrations.RenameField(
            model_name='thisserverconfiguration',
            old_name='connection_gitlab_group_id',
            new_name='connection_git_lab_group_id',
        ),
        migrations.RenameField(
            model_name='thisserverconfiguration',
            old_name='connection_gitlab_hostname',
            new_name='connection_git_lab_hostname',
        ),
        migrations.RenameField(
            model_name='thisserverconfiguration',
            old_name='connection_gitlab_token',
            new_name='connection_git_lab_token',
        ),
    ]
