# Generated by Django 5.1.6 on 2025-02-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_rename_application_group_application_application_group_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_legacy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
