# Generated by Django 5.1.6 on 2025-02-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_application_link_gitlab_wiki_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='encrypted_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='encrypted_username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
