# Generated by Django 5.1.6 on 2025-02-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_database_encrypted_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='encrypted_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='encrypted_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
