# Generated by Django 5.1.6 on 2025-02-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_database_encrypted_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='ip_v4_internal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
