# Generated by Django 5.1.6 on 2025-03-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_cached_number_of_code_reviews_historicalsprint_cached_total_number_of_merge_requests_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='kpi_developers_to_exclude',
            field=models.ManyToManyField(blank=True, to='core.person'),
        ),
    ]
