# Generated by Django 5.1.6 on 2025-02-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_database_hostname_database_ip_v4_internal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='schema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
