# Generated by Django 5.1.6 on 2025-03-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_thisserverconfiguration_kpi_developers_to_exclude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalthisserverconfiguration',
            old_name='connection_git_lab_group_id',
            new_name='connection_git_lab_top_level_group_id',
        ),
        migrations.RenameField(
            model_name='thisserverconfiguration',
            old_name='connection_git_lab_group_id',
            new_name='connection_git_lab_top_level_group_id',
        ),
    ]
