# Generated by Django 5.1.7 on 2025-03-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_connection_git_lab_group_id_historicalthisserverconfiguration_connection_git_lab_top_level_gr'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='core.person'),
        ),
    ]
