# Generated by Django 5.1.6 on 2025-02-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_application_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationgroup',
            options={'ordering': ['name', '-id']},
        ),
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['schema', '-id']},
        ),
        migrations.AlterModelOptions(
            name='dependency',
            options={'ordering': ['name', 'type_programing_concept', 'version', '-id'], 'verbose_name_plural': 'Dependencies'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['name', '-id']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name_last', 'name_first', 'id'], 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-version', '-id']},
        ),
        migrations.AlterModelOptions(
            name='releasebundle',
            options={'ordering': ['name', '-id']},
        ),
    ]
