# Generated by Django 5.1.7 on 2025-10-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_externalblockers_historicalexternalblockers'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='language',
            field=models.CharField(blank=True, choices=[('bash', 'Bash'), ('python', 'Python'), ('javascript', 'JavaScript'), ('sql', 'SQL'), ('other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcommand',
            name='language',
            field=models.CharField(blank=True, choices=[('bash', 'Bash'), ('python', 'Python'), ('javascript', 'JavaScript'), ('sql', 'SQL'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
