# Generated by Django 5.1.6 on 2025-02-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_application_is_required_to_adhere_to_california_consumer_privacy_act_ccpa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acronym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name', 'acronym', '-id'],
            },
        ),
    ]
