# Generated by Django 5.1.7 on 2025-10-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_migrate_role_booleans_to_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperson',
            name='is_architect',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='is_developer',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='is_lead_developer',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='is_product_manager',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='is_product_owner',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='is_project_manager',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='is_scrum_master',
        ),
        migrations.RemoveField(
            model_name='historicalperson',
            name='is_stakeholder',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_architect',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_developer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_lead_developer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_product_manager',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_product_owner',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_project_manager',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_scrum_master',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_stakeholder',
        ),
    ]
