# Generated by Django 5.1.6 on 2025-02-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='link_support_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
