# Generated by Django 5.1.7 on 2025-10-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_historicalperson_is_architect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='is_protected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_protected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
