# Generated by Django 5.1.7 on 2025-10-11 19:17

from django.db import migrations


def protect_stakeholder_role(apps, schema_editor):
    """
    Mark the Stakeholder role as protected to prevent deletion.
    This role is critical to the application and must always exist.
    """
    Role = apps.get_model('core', 'Role')

    # Get or create the Stakeholder role
    stakeholder_role, created = Role.objects.get_or_create(
        name='Stakeholder',
        defaults={
            'acronym': None,
            'aliases_csv': None,
            'comment': 'A person or group with an interest or concern in the application. This is a protected role required by the system.',
            'is_protected': True,
        }
    )

    if created:
        print("✓ Created Stakeholder role and marked as protected")
    else:
        # Update existing Stakeholder role to be protected
        if not stakeholder_role.is_protected:
            stakeholder_role.is_protected = True
            if not stakeholder_role.comment:
                stakeholder_role.comment = 'A person or group with an interest or concern in the application. This is a protected role required by the system.'
            stakeholder_role.save()
            print("✓ Marked existing Stakeholder role as protected")
        else:
            print("✓ Stakeholder role already protected")


def unprotect_stakeholder_role(apps, schema_editor):
    """
    Reverse migration: unprotect the Stakeholder role.
    """
    Role = apps.get_model('core', 'Role')

    try:
        stakeholder_role = Role.objects.get(name='Stakeholder')
        stakeholder_role.is_protected = False
        stakeholder_role.save()
        print("✓ Unprotected Stakeholder role")
    except Role.DoesNotExist:
        print("⚠ Stakeholder role does not exist")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_historicalrole_is_protected_role_is_protected'),
    ]

    operations = [
        migrations.RunPython(protect_stakeholder_role, unprotect_stakeholder_role),
    ]
