# Generated by Django 5.1.7 on 2025-10-11 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_protect_stakeholder_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='connection_google_maps_api_key',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.secret'),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='connection_google_maps_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='server_config_google_maps', to='core.secret'),
        ),
    ]
