# Generated by Django 5.1.6 on 2025-02-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_client_cronjob_datapoint_datauseexception_hotfix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name_pronunciation',
            new_name='pronunciation',
        ),
        migrations.AddField(
            model_name='acronym',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
