# Generated by Django 5.1.7 on 2025-10-28 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_aivendor_aigovernance_aiusecase_aihallucination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusecase',
            name='affected_groups_consultation_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='agency_has_code_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='agency_owned_training_data_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='ai_impact_assessment_conducted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='ai_system_outputs_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='ai_use_notice_approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='ato_system_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='caio_determination_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='can_ai_act_without_human_involvement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ai_use_cases', to='core.client'),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='data_science_tools_reuse_approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='date_deployed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='date_development_or_acquisition_began',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='date_initiated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='date_retired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='demographic_variables_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='developed_under_contract_or_inhouse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='development_lifecycle_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='disparities_detection_mitigation_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='disseminates_info_to_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='has_access_to_enterprise_data_catalog',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='has_ato_for_ai_system',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='has_computing_resources_request_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='has_fallback_and_escalation_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='has_model_training_data_documentation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='has_opt_out_mechanism',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='has_post_deployment_monitoring_process',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='hisp_supporting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='includes_custom_developed_code',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='independent_evaluation_conducted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='info_made_available_for_review',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='info_quality_act_compliance_approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='intended_purpose_and_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='involves_pii_maintained_by_client',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='is_currently_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='is_in_commercial_ai_products_list',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='is_provisioning_communication_timely',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='is_rights_impacting',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='is_safety_impacting',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='is_used_for_decisions_with_adverse_impact',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='it_infrastructure_provisioning_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='key_risks_and_identification_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='open_source_code_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='presumed_rights_impacting_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='presumed_safety_impacting_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='procurement_instrument_identifiers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='public_facing_service_supporting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='requested_extension_for_risk_management',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='saop_assessed_privacy_risks',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='supports_hisp_public_facing_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='tested_in_operational_environment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='use_case_topic_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='uses_face_recognition_or_capture',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='aiusecase',
            name='wait_time_for_developer_tools',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='affected_groups_consultation_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='agency_has_code_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='agency_owned_training_data_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='ai_impact_assessment_conducted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='ai_system_outputs_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='ai_use_notice_approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='ato_system_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='caio_determination_justification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='can_ai_act_without_human_involvement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.client'),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='data_science_tools_reuse_approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='date_deployed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='date_development_or_acquisition_began',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='date_initiated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='date_retired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='demographic_variables_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='developed_under_contract_or_inhouse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='development_lifecycle_stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='disparities_detection_mitigation_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='disseminates_info_to_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='has_access_to_enterprise_data_catalog',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='has_ato_for_ai_system',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='has_computing_resources_request_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='has_fallback_and_escalation_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='has_model_training_data_documentation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='has_opt_out_mechanism',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='has_post_deployment_monitoring_process',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='hisp_supporting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='includes_custom_developed_code',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='independent_evaluation_conducted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='info_made_available_for_review',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='info_quality_act_compliance_approach',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='intended_purpose_and_benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='involves_pii_maintained_by_client',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='is_currently_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='is_in_commercial_ai_products_list',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='is_provisioning_communication_timely',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='is_rights_impacting',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='is_safety_impacting',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='is_used_for_decisions_with_adverse_impact',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='it_infrastructure_provisioning_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='key_risks_and_identification_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='open_source_code_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='presumed_rights_impacting_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='presumed_safety_impacting_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='procurement_instrument_identifiers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='public_facing_service_supporting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='requested_extension_for_risk_management',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='saop_assessed_privacy_risks',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='supports_hisp_public_facing_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='tested_in_operational_environment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='use_case_topic_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='uses_face_recognition_or_capture',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalaiusecase',
            name='wait_time_for_developer_tools',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
