# Generated by Django 5.1.7 on 2025-10-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_estimation_estimationitem_historicalestimation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationitem',
            name='complexity_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='cone_of_uncertainty',
            field=models.CharField(blank=True, choices=[('INITIAL_CONCEPT', 'Initial Concept (4x uncertainty)'), ('APPROVED_PRODUCT', 'Approved Product Definition (2x uncertainty)'), ('REQUIREMENTS_COMPLETE', 'Requirements Complete (1.5x uncertainty)'), ('DESIGN_COMPLETE', 'Design Complete (1.25x uncertainty)'), ('IMPLEMENTATION_COMPLETE', 'Implementation Complete (1.1x uncertainty)')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='priority',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='uncertainty_padding_factor',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='complexity_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='cone_of_uncertainty',
            field=models.CharField(blank=True, choices=[('INITIAL_CONCEPT', 'Initial Concept (4x uncertainty)'), ('APPROVED_PRODUCT', 'Approved Product Definition (2x uncertainty)'), ('REQUIREMENTS_COMPLETE', 'Requirements Complete (1.5x uncertainty)'), ('DESIGN_COMPLETE', 'Design Complete (1.25x uncertainty)'), ('IMPLEMENTATION_COMPLETE', 'Implementation Complete (1.1x uncertainty)')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='priority',
            field=models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='uncertainty_padding_factor',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
