# Generated by Django 5.1.6 on 2025-02-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_person_job_level_person_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='service_providers',
            field=models.ManyToManyField(blank=True, related_name='applications_that_use_service_provider', to='core.serviceprovider'),
        ),
        migrations.AddField(
            model_name='application',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='applications_that_use_tool', to='core.tool'),
        ),
    ]
