# Generated by Django 5.1.6 on 2025-02-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_application_service_providers_application_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='is_for_spsrd',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_functional_requirement',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovidersecurityrequirementsdocument',
            name='applications',
            field=models.ManyToManyField(blank=True, to='core.application'),
        ),
        migrations.AddField(
            model_name='serviceprovidersecurityrequirementsdocument',
            name='clients',
            field=models.ManyToManyField(blank=True, to='core.client'),
        ),
        migrations.AddField(
            model_name='serviceprovidersecurityrequirementsdocument',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='core.requirement'),
        ),
    ]
