# Generated by Django 5.1.7 on 2025-10-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_estimationitem_complexity_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimationitem',
            name='uncertainty_padding_factor',
        ),
        migrations.RemoveField(
            model_name='historicalestimationitem',
            name='uncertainty_padding_factor',
        ),
    ]
