# Generated by Django 5.1.6 on 2025-02-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_requirement_is_for_spsrd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acronym',
            name='supporting_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
