# Generated by Django 5.1.7 on 2025-10-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_estimationitem_uncertainty_padding_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationitem',
            name='code_review_hours_junior',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='code_review_hours_lead',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='code_review_hours_mid',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='code_review_hours_senior',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='tests_hours_junior',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='tests_hours_lead',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='tests_hours_mid',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='tests_hours_senior',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='code_review_hours_junior',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='code_review_hours_lead',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='code_review_hours_mid',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='code_review_hours_senior',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='tests_hours_junior',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='tests_hours_lead',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='tests_hours_mid',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='tests_hours_senior',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
