# Generated by Django 5.1.7 on 2025-10-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_estimationitem_code_review_hours_junior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationitem',
            name='code_reviewer_hours',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='code_reviewer_hours',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
