# Generated by Django 5.1.6 on 2025-02-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_acronym_supporting_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name', '-id'],
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_for_soc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
