# Generated by Django 5.1.6 on 2025-02-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_report_requirement_is_for_soc'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='applications',
            field=models.ManyToManyField(blank=True, to='core.application'),
        ),
    ]
