# Generated by Django 5.1.7 on 2025-10-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_add_order_to_estimation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationitem',
            name='story_points',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='estimationitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='story_points',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
