# Generated by Django 5.1.7 on 2025-10-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_add_title_and_story_points_to_estimation_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='junior_developer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='lead_developer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='mid_developer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='reviewer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='senior_developer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimation',
            name='junior_developer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimation',
            name='lead_developer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimation',
            name='mid_developer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimation',
            name='reviewer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimation',
            name='senior_developer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
