# Generated by Django 5.1.7 on 2025-10-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_estimation_junior_developer_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='reviewer_count',
        ),
        migrations.RemoveField(
            model_name='historicalestimation',
            name='reviewer_count',
        ),
    ]
