# Generated by Django 5.1.7 on 2025-10-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_estimation_reviewer_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='sprint_duration_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimation',
            name='sprint_duration_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
