# Generated by Django 5.1.7 on 2025-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_estimation_sprint_duration_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationitem',
            name='group',
            field=models.CharField(blank=True, help_text="Optional category/group name for organizing related items (e.g., 'Frontend', 'Backend', 'Database')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalestimationitem',
            name='group',
            field=models.CharField(blank=True, help_text="Optional category/group name for organizing related items (e.g., 'Frontend', 'Backend', 'Database')", max_length=200, null=True),
        ),
    ]
