# Generated by Django 5.1.7 on 2025-10-29 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_estimationitem_group_historicalestimationitem_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='connection_chatgpt_api_key',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.secret'),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='connection_chatgpt_api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='server_config_chatgpt', to='core.secret'),
        ),
    ]
