# Generated by Django 5.1.7 on 2025-10-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_historicalthisserverconfiguration_connection_chatgpt_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='story_points_modifier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text="Multiplier for auto-calculated story points to calibrate to your team's velocity (default: 1.0)", max_digits=5),
        ),
        migrations.AddField(
            model_name='historicalestimation',
            name='story_points_modifier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text="Multiplier for auto-calculated story points to calibrate to your team's velocity (default: 1.0)", max_digits=5),
        ),
    ]
