# Generated by Django 5.1.7 on 2025-10-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_estimation_story_points_modifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationitem',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='estimation_items', to='core.link'),
        ),
    ]
