# Generated by Django 5.1.7 on 2025-10-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_estimationitem_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallink',
            name='click_count',
            field=models.IntegerField(default=0, help_text='Number of times this link has been accessed via short URL'),
        ),
        migrations.AddField(
            model_name='historicallink',
            name='first_accessed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the link was first accessed via short URL', null=True),
        ),
        migrations.AddField(
            model_name='historicallink',
            name='is_short_url_active',
            field=models.BooleanField(default=True, help_text='Whether the short URL is active and can be used for redirects'),
        ),
        migrations.AddField(
            model_name='historicallink',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the link was last accessed via short URL', null=True),
        ),
        migrations.AddField(
            model_name='historicallink',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique short code for generating short URLs (e.g., "abc123"). Auto-generated if left blank.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='click_count',
            field=models.IntegerField(default=0, help_text='Number of times this link has been accessed via short URL'),
        ),
        migrations.AddField(
            model_name='link',
            name='first_accessed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the link was first accessed via short URL', null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='is_short_url_active',
            field=models.BooleanField(default=True, help_text='Whether the short URL is active and can be used for redirects'),
        ),
        migrations.AddField(
            model_name='link',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the link was last accessed via short URL', null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, help_text='Unique short code for generating short URLs (e.g., "abc123"). Auto-generated if left blank.', max_length=50, null=True, unique=True),
        ),
    ]
