# Generated by Django 5.1.7 on 2025-10-30 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_historicallink_click_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='project_manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects_managed', to='core.person'),
        ),
    ]
