# Generated by Django 5.1.7 on 2025-10-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_billingcode_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('proposal_approved', 'Proposal Approved'), ('beta_launch', 'Beta Launch'), ('soft_launch', 'Soft Launch'), ('launched', 'Launched'), ('on_hold', 'On Hold'), ('denied', 'Denied')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('proposal_approved', 'Proposal Approved'), ('beta_launch', 'Beta Launch'), ('soft_launch', 'Soft Launch'), ('launched', 'Launched'), ('on_hold', 'On Hold'), ('denied', 'Denied')], max_length=255, null=True),
        ),
    ]
