# Generated by Django 5.1.7 on 2025-10-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_historicalproject_status_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='estimations', to='core.link'),
        ),
    ]
