# Generated by Django 5.1.7 on 2025-10-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_estimation_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='group_order',
            field=models.JSONField(blank=True, default=list, help_text='Order of groups for display (list of group names)'),
        ),
        migrations.AddField(
            model_name='historicalestimation',
            name='group_order',
            field=models.JSONField(blank=True, default=list, help_text='Order of groups for display (list of group names)'),
        ),
    ]
