# Generated by Django 5.1.7 on 2025-10-31 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_estimation_group_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcode',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='billingcode',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replaced_by_codes', to='core.billingcode'),
        ),
        migrations.AddField(
            model_name='historicalbillingcode',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbillingcode',
            name='replaces',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.billingcode'),
        ),
    ]
