# Generated by Django 5.1.7 on 2025-11-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_billingcode_is_active_billingcode_replaces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='pipeline_status',
            field=models.CharField(blank=True, choices=[('Failing', 'Failing'), ('Passing', 'Passing'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='pipeline_status',
            field=models.CharField(blank=True, choices=[('Failing', 'Failing'), ('Passing', 'Passing'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
    ]
