# Generated by Django 5.1.7 on 2025-11-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_application_pipeline_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='centralized_logging_status',
            field=models.CharField(blank=True, choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='centralized_logging_status',
            field=models.CharField(blank=True, choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('Unknown', 'Unknown')], max_length=255, null=True),
        ),
    ]
