# Generated by Django 5.1.7 on 2025-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_application_centralized_logging_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='gitlab_sync_max_group_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='gitlab_sync_max_pipelines_per_project',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='gitlab_sync_max_projects_per_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='gitlab_sync_pipelines_days_back',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='gitlab_sync_max_group_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='gitlab_sync_max_pipelines_per_project',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='gitlab_sync_max_projects_per_group',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='gitlab_sync_pipelines_days_back',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
