# Generated by Django 5.1.7 on 2025-11-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_historicalthisserverconfiguration_gitlab_sync_max_group_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='gitlab_sync_operation_timeout_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='gitlab_sync_operation_timeout_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
