# Generated by Django 5.1.7 on 2025-11-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_add_gitlab_sync_operation_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='gitlab_sync_skip_group_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='gitlab_sync_skip_group_ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
