# Generated by Django 5.1.7 on 2025-11-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_gitlab_sync_skip_group_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='gitlab_sync_commits_days_back',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='gitlab_sync_max_issues_per_project',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='gitlab_sync_max_merge_requests_per_project',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='gitlab_sync_commits_days_back',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='gitlab_sync_max_issues_per_project',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='gitlab_sync_max_merge_requests_per_project',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
