# Generated by Django 5.1.7 on 2025-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_add_gitlab_sync_limits_for_commits_issues_mrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthisserverconfiguration',
            name='gitlab_sync_max_events_per_project',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thisserverconfiguration',
            name='gitlab_sync_max_events_per_project',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
