# Generated by Django 5.1.7 on 2025-11-05 23:51

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_historicalthisserverconfiguration_gitlab_sync_max_events_per_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseSizeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size_bytes', models.BigIntegerField(help_text='Size of table data in bytes')),
                ('index_size_bytes', models.BigIntegerField(default=0, help_text='Size of table indexes in bytes')),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this snapshot was recorded')),
            ],
            options={
                'verbose_name': 'Database Size History',
                'verbose_name_plural': 'Database Size Histories',
                'ordering': ['-recorded_at', 'table_name'],
                'indexes': [models.Index(fields=['table_name', '-recorded_at'], name='core_databa_table_n_a7bf63_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDatabaseSizeHistory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('table_name', models.CharField(blank=True, max_length=255, null=True)),
                ('size_bytes', models.BigIntegerField(help_text='Size of table data in bytes')),
                ('index_size_bytes', models.BigIntegerField(default=0, help_text='Size of table indexes in bytes')),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, editable=False, help_text='When this snapshot was recorded')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '_Historical Record for DatabaseSizeHistory',
                'verbose_name_plural': '_Historical Records for DatabaseSizeHistory',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
