# Generated by Django 5.1.7 on 2025-11-24 23:18

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_databasesizehistory_historicaldatabasesizehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProcedureStep',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this step (lower numbers appear first)')),
                ('step_type', models.CharField(choices=[('markdown', 'Markdown Text'), ('code', 'Code Block'), ('file_reference', 'File Reference'), ('checklist', 'Checklist Item')], default='markdown', help_text='Type of procedure step', max_length=50)),
                ('step_data', models.JSONField(blank=True, default=dict, help_text='Type-specific configuration stored as JSON')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, help_text='Application this step belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.application')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '_Historical Record for ProcedureStep',
                'verbose_name_plural': '_Historical Records for ProcedureStep',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProcedureStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of this step (lower numbers appear first)')),
                ('step_type', models.CharField(choices=[('markdown', 'Markdown Text'), ('code', 'Code Block'), ('file_reference', 'File Reference'), ('checklist', 'Checklist Item')], default='markdown', help_text='Type of procedure step', max_length=50)),
                ('step_data', models.JSONField(blank=True, default=dict, help_text='Type-specific configuration stored as JSON')),
                ('application', models.ForeignKey(help_text='Application this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='procedure_steps', to='core.application')),
            ],
            options={
                'ordering': ['application', 'order', 'id'],
                'indexes': [models.Index(fields=['application', 'order'], name='core_proced_applica_11ab9e_idx')],
            },
        ),
    ]
