# Generated by Django 5.1.7 on 2025-12-01 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_add_procedure_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcode',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_codes_managed', to='core.person'),
        ),
        migrations.AddField(
            model_name='historicalbillingcode',
            name='project_manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person'),
        ),
    ]
