# Generated by Django 5.1.7 on 2025-12-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_billingcode_project_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcode',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_codes', to='core.team'),
        ),
        migrations.AddField(
            model_name='historicalbillingcode',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.team'),
        ),
    ]
