# Generated by Django 5.1.7 on 2025-12-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_billingcode_team_historicalbillingcode_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='person_smes',
            field=models.ManyToManyField(blank=True, related_name='applications_sme_of', to='core.person'),
        ),
    ]
