# Generated by Django 5.1.7 on 2025-12-02 01:40

from django.db import migrations


def create_and_protect_sme_role(apps, schema_editor):
    """
    Create and mark the SME (Subject Matter Expert) role as protected.
    This role is critical to the application and must always exist.
    """
    Role = apps.get_model('core', 'Role')

    # Get or create the SME role
    sme_role, created = Role.objects.get_or_create(
        name='SME',
        defaults={
            'acronym': None,
            'aliases_csv': 'Subject Matter Expert',
            'comment': 'A Subject Matter Expert with specialized knowledge or expertise in the application domain. This is a protected role required by the system.',
            'is_protected': True,
        }
    )

    if created:
        print("✓ Created SME role and marked as protected")
    else:
        # Update existing SME role to be protected
        if not sme_role.is_protected:
            sme_role.is_protected = True
            if not sme_role.comment:
                sme_role.comment = 'A Subject Matter Expert with specialized knowledge or expertise in the application domain. This is a protected role required by the system.'
            if not sme_role.aliases_csv:
                sme_role.aliases_csv = 'Subject Matter Expert'
            sme_role.save()
            print("✓ Marked existing SME role as protected")
        else:
            print("✓ SME role already protected")


def unprotect_sme_role(apps, schema_editor):
    """
    Reverse migration: unprotect the SME role.
    """
    Role = apps.get_model('core', 'Role')

    try:
        sme_role = Role.objects.get(name='SME')
        sme_role.is_protected = False
        sme_role.save()
        print("✓ Unprotected SME role")
    except Role.DoesNotExist:
        print("⚠ SME role does not exist")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_add_sme_field_to_application'),
    ]

    operations = [
        migrations.RunPython(create_and_protect_sme_role, unprotect_sme_role),
    ]
