# Generated by Django 5.1.7 on 2025-12-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_add_application_pin_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='applications', to='core.link'),
        ),
    ]
