# Generated by Django 5.1.7 on 2025-12-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_historicalrecommendation_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-date_recommended', '-id']},
        ),
        migrations.RemoveField(
            model_name='historicalrecommendation',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='historicalrecommendation',
            name='date_target_completion',
        ),
        migrations.RemoveField(
            model_name='historicalrecommendation',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='historicalrecommendation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='date_target_completion',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='status',
        ),
    ]
