# Generated by Django 5.1.7 on 2025-12-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='core.link'),
        ),
    ]
