# Generated by Django 5.1.7 on 2025-12-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_recommendation_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrecommendation',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrecommendation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrecommendation',
            name='rationale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrecommendation',
            name='risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='rationale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='risks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
