# Generated by Django 5.1.7 on 2025-12-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_api_apiauthentication_apirequest_apirequestexecution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='default_environment',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Local', 'Local'), ('Production', 'Production'), ('Production External', 'Production External'), ('Staging', 'Staging')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='type_environment',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Local', 'Local'), ('Production', 'Production'), ('Production External', 'Production External'), ('Staging', 'Staging')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapirequest',
            name='default_environment',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Local', 'Local'), ('Production', 'Production'), ('Production External', 'Production External'), ('Staging', 'Staging')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldatabase',
            name='type_environment',
            field=models.CharField(blank=True, choices=[('Development', 'Development'), ('Local', 'Local'), ('Production', 'Production'), ('Production External', 'Production External'), ('Staging', 'Staging')], max_length=255, null=True),
        ),
    ]
