# Generated by Django 5.1.7 on 2025-12-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_add_production_external_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, help_text='Form data key-value pairs for x-www-form-urlencoded requests', null=True),
        ),
        migrations.AddField(
            model_name='historicalapirequest',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, help_text='Form data key-value pairs for x-www-form-urlencoded requests', null=True),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='request_body',
            field=models.TextField(blank=True, help_text='Request body (JSON, XML, or raw text)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalapirequest',
            name='request_body',
            field=models.TextField(blank=True, help_text='Request body (JSON, XML, or raw text)', null=True),
        ),
    ]
