# Generated by Django 5.1.7 on 2025-12-16 00:33

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_historicalitdevopsrequest_itdevopsrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address_continued', models.CharField(blank=True, max_length=255, null=True)),
                ('location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('location_county', models.CharField(blank=True, max_length=255, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('location_postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('location_state_code', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia'), ('MP', 'Northern Mariana Islands'), ('GU', 'Guam'), ('VI', 'Virgin Islands'), ('PW', 'Palau'), ('FM', 'Federated States of Micronesia'), ('MH', 'Marshall Islands'), ('AS', 'American Samoa'), ('PI', 'Puerto Rico')], max_length=255, null=True)),
                ('primary_products', models.CharField(blank=True, max_length=255, null=True)),
                ('market_segment', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_count_tier', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000'), ('5001-10000', '5001-10000'), ('10000+', '10000+')], max_length=255, null=True)),
                ('revenue_tier', models.CharField(blank=True, choices=[('$0-$1M', '$0-$1M'), ('$1M-$10M', '$1M-$10M'), ('$10M-$50M', '$10M-$50M'), ('$50M-$100M', '$50M-$100M'), ('$100M-$500M', '$100M-$500M'), ('$500M-$1B', '$500M-$1B'), ('$1B-$5B', '$1B-$5B'), ('$5B-$10B', '$5B-$10B'), ('$10B+', '$10B+')], max_length=255, null=True)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('competing_applications', models.ManyToManyField(blank=True, related_name='competitors', to='core.application')),
                ('organizations', models.ManyToManyField(blank=True, related_name='competitors', to='core.organization')),
            ],
            options={
                'verbose_name': 'Competitor',
                'verbose_name_plural': 'Competitors',
                'ordering': ['name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCompetitor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address_continued', models.CharField(blank=True, max_length=255, null=True)),
                ('location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('location_county', models.CharField(blank=True, max_length=255, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('location_postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('location_state_code', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia'), ('MP', 'Northern Mariana Islands'), ('GU', 'Guam'), ('VI', 'Virgin Islands'), ('PW', 'Palau'), ('FM', 'Federated States of Micronesia'), ('MH', 'Marshall Islands'), ('AS', 'American Samoa'), ('PI', 'Puerto Rico')], max_length=255, null=True)),
                ('primary_products', models.CharField(blank=True, max_length=255, null=True)),
                ('market_segment', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_count_tier', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000'), ('5001-10000', '5001-10000'), ('10000+', '10000+')], max_length=255, null=True)),
                ('revenue_tier', models.CharField(blank=True, choices=[('$0-$1M', '$0-$1M'), ('$1M-$10M', '$1M-$10M'), ('$10M-$50M', '$10M-$50M'), ('$50M-$100M', '$50M-$100M'), ('$100M-$500M', '$100M-$500M'), ('$500M-$1B', '$500M-$1B'), ('$1B-$5B', '$1B-$5B'), ('$5B-$10B', '$5B-$10B'), ('$10B+', '$10B+')], max_length=255, null=True)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '_Historical Record for Competitor',
                'verbose_name_plural': '_Historical Records for Competitor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
