# Generated by Django 5.1.7 on 2025-12-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_url_field_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='itdevopsrequest',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='it_devops_requests', to='core.link'),
        ),
    ]
