# Generated by Django 5.1.7 on 2025-12-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_itdevopsrequest_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(blank=True, choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=255, null=True),
        ),
    ]
