# Generated by Django 5.1.7 on 2025-12-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_historicaltask_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
