# Generated by Django 5.1.7 on 2025-12-31 17:50

from django.db import migrations


def populate_task_order(apps, schema_editor):
    """Populate order field for existing tasks with incremental values"""
    Task = apps.get_model('core', 'Task')

    # Get all tasks ordered by id (creation order)
    tasks = Task.objects.filter(order__isnull=True).order_by('id')

    # Assign incremental order values
    for index, task in enumerate(tasks, start=1):
        task.order = index
        task.save(update_fields=['order'])


def reverse_populate_task_order(apps, schema_editor):
    """Reverse migration - set order back to None"""
    Task = apps.get_model('core', 'Task')
    Task.objects.all().update(order=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_task_options_historicaltask_order_task_order'),
    ]

    operations = [
        migrations.RunPython(populate_task_order, reverse_populate_task_order),
    ]
