# Generated by Django 5.1.7 on 2025-12-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_populate_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='applications', to='core.document'),
        ),
    ]
