# Generated by Django 5.1.7 on 2026-01-08 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_application_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
