# Generated by Django 5.1.7 on 2026-01-08 19:03

from django.db import migrations


def migrate_bookmarks_forward(apps, schema_editor):
    """
    Migrate existing bookmarks from Link.bookmarked_by M2M to UserBookmark model.
    All existing bookmarks will be placed at root level (folder=None).
    """
    Link = apps.get_model('core', 'Link')
    UserBookmark = apps.get_model('core', 'UserBookmark')

    # Get all links with bookmarks
    links = Link.objects.prefetch_related('bookmarked_by').all()

    user_bookmarks_to_create = []
    for link in links:
        for user in link.bookmarked_by.all():
            user_bookmarks_to_create.append(
                UserBookmark(
                    user=user,
                    link=link,
                    folder=None,  # Root level
                    order=0,
                )
            )

    # Bulk create all UserBookmark records
    if user_bookmarks_to_create:
        UserBookmark.objects.bulk_create(user_bookmarks_to_create, ignore_conflicts=True)
        print(f"Migrated {len(user_bookmarks_to_create)} bookmarks to UserBookmark model")


def migrate_bookmarks_backward(apps, schema_editor):
    """
    Reverse migration: Copy UserBookmark records back to Link.bookmarked_by M2M.
    """
    Link = apps.get_model('core', 'Link')
    UserBookmark = apps.get_model('core', 'UserBookmark')

    # Get all user bookmarks
    user_bookmarks = UserBookmark.objects.select_related('user', 'link').all()

    for bookmark in user_bookmarks:
        if bookmark.link and bookmark.user:
            bookmark.link.bookmarked_by.add(bookmark.user)

    print(f"Reversed migration for {user_bookmarks.count()} bookmarks")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_historicaluser_bookmark_view_preference_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_bookmarks_forward, migrate_bookmarks_backward),
    ]
