# Generated by Django 5.1.7 on 2026-01-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_migrate_bookmarks_to_user_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='bookmarked_by',
        ),
    ]
