# Generated by Django 5.1.7 on 2026-01-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_remove_link_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkfolder',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code (e.g., #3B82F6)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='historicalbookmarkfolder',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code (e.g., #3B82F6)', max_length=7, null=True),
        ),
    ]
