# Generated by Django 5.1.7 on 2026-01-08 20:14

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_bookmarkfolder_color_historicalbookmarkfolder_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_occurred', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of what happened', null=True)),
                ('evidence_blob_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence_blob_data', models.BinaryField(blank=True, null=True)),
                ('evidence_blob_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence_blob_size', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=255, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bad_interactions', to='core.person')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported_bad_interactions', to='core.person')),
            ],
            options={
                'verbose_name': 'Bad Interaction',
                'verbose_name_plural': 'Bad Interactions',
                'ordering': ['-date_occurred', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBadInteraction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_occurred', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of what happened', null=True)),
                ('evidence_blob_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence_blob_data', models.BinaryField(blank=True, null=True)),
                ('evidence_blob_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence_blob_size', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person')),
                ('reported_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person')),
            ],
            options={
                'verbose_name': '_Historical Record for BadInteraction',
                'verbose_name_plural': '_Historical Records for BadInteraction',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHRIncident',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_filed', models.DateField(blank=True, null=True)),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description', null=True)),
                ('resolution', models.TextField(blank=True, help_text='Resolution details', null=True)),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('filed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person')),
            ],
            options={
                'verbose_name': '_Historical Record for HRIncident',
                'verbose_name_plural': '_Historical Records for HRIncident',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HRIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_filed', models.DateField(blank=True, null=True)),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description', null=True)),
                ('resolution', models.TextField(blank=True, help_text='Resolution details', null=True)),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], max_length=255, null=True)),
                ('bad_interactions', models.ManyToManyField(blank=True, related_name='hr_incidents', to='core.badinteraction')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='filed_hr_incidents', to='core.person')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hr_incidents', to='core.person')),
            ],
            options={
                'verbose_name': 'HR Incident',
                'verbose_name_plural': 'HR Incidents',
                'ordering': ['-date_filed', 'id'],
            },
        ),
    ]
