# Generated by Django 5.1.7 on 2026-01-08 20:36

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_badinteraction_historicalbadinteraction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhrincident',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hrincident',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BadInteractionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('attachment_blob_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_blob_data', models.BinaryField(blank=True, null=True)),
                ('attachment_blob_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_blob_size', models.IntegerField(blank=True, null=True)),
                ('bad_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updates', to='core.badinteraction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bad_interaction_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bad Interaction Update',
                'verbose_name_plural': 'Bad Interaction Updates',
                'ordering': ['datetime_created', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBadInteractionUpdate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(blank=True, editable=False)),
                ('attachment_blob_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_blob_data', models.BinaryField(blank=True, null=True)),
                ('attachment_blob_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_blob_size', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bad_interaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.badinteraction')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '_Historical Record for BadInteractionUpdate',
                'verbose_name_plural': '_Historical Records for BadInteractionUpdate',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHRIncidentUpdate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(blank=True, editable=False)),
                ('attachment_blob_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_blob_data', models.BinaryField(blank=True, null=True)),
                ('attachment_blob_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_blob_size', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hr_incident', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.hrincident')),
            ],
            options={
                'verbose_name': '_Historical Record for HRIncidentUpdate',
                'verbose_name_plural': '_Historical Records for HRIncidentUpdate',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HRIncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('attachment_blob_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_blob_data', models.BinaryField(blank=True, null=True)),
                ('attachment_blob_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment_blob_size', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hr_incident_updates', to=settings.AUTH_USER_MODEL)),
                ('hr_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updates', to='core.hrincident')),
            ],
            options={
                'verbose_name': 'HR Incident Update',
                'verbose_name_plural': 'HR Incident Updates',
                'ordering': ['datetime_created', 'id'],
            },
        ),
    ]
