# Generated by Django 5.1.7 on 2026-01-09 04:55

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_historicalmaintenancewindow_maintenancewindow'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMeeting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address_continued', models.CharField(blank=True, max_length=255, null=True)),
                ('location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('location_county', models.CharField(blank=True, max_length=255, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('location_postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('location_state_code', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia'), ('MP', 'Northern Mariana Islands'), ('GU', 'Guam'), ('VI', 'Virgin Islands'), ('PW', 'Palau'), ('FM', 'Federated States of Micronesia'), ('MH', 'Marshall Islands'), ('AS', 'American Samoa'), ('PI', 'Puerto Rico')], max_length=255, null=True)),
                ('datetime_start', models.DateTimeField(blank=True, null=True)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('minutes', models.TextField(blank=True, null=True)),
                ('meeting_type', models.CharField(blank=True, choices=[('team', 'Team Meeting'), ('client', 'Client/Stakeholder'), ('one_on_one', 'One-on-One'), ('general', 'General')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=255, null=True)),
                ('virtual_meeting_url', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.application')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.project')),
            ],
            options={
                'verbose_name': '_Historical Record for Meeting',
                'verbose_name_plural': '_Historical Records for Meeting',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address_continued', models.CharField(blank=True, max_length=255, null=True)),
                ('location_city', models.CharField(blank=True, max_length=255, null=True)),
                ('location_county', models.CharField(blank=True, max_length=255, null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('location_postal_code', models.CharField(blank=True, max_length=255, null=True)),
                ('location_state_code', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia'), ('MP', 'Northern Mariana Islands'), ('GU', 'Guam'), ('VI', 'Virgin Islands'), ('PW', 'Palau'), ('FM', 'Federated States of Micronesia'), ('MH', 'Marshall Islands'), ('AS', 'American Samoa'), ('PI', 'Puerto Rico')], max_length=255, null=True)),
                ('datetime_start', models.DateTimeField(blank=True, null=True)),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('minutes', models.TextField(blank=True, null=True)),
                ('meeting_type', models.CharField(blank=True, choices=[('team', 'Team Meeting'), ('client', 'Client/Stakeholder'), ('one_on_one', 'One-on-One'), ('general', 'General')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=255, null=True)),
                ('virtual_meeting_url', models.CharField(blank=True, max_length=255, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetings', to='core.application')),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings_attended', to='core.person')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetings_organized', to='core.person')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetings', to='core.project')),
            ],
            options={
                'ordering': ['-datetime_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMeetingActionItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], max_length=255, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assignee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.meeting')),
            ],
            options={
                'verbose_name': '_Historical Record for MeetingActionItem',
                'verbose_name_plural': '_Historical Records for MeetingActionItem',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], max_length=255, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_items_assigned', to='core.person')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_items', to='core.meeting')),
            ],
            options={
                'ordering': ['status', '-priority', 'due_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['datetime_start'], name='core_meetin_datetim_a2148e_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['datetime_end'], name='core_meetin_datetim_967074_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status'], name='core_meetin_status_3bca30_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_type'], name='core_meetin_meeting_5ce950_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['status'], name='core_meetin_status_dedd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['priority'], name='core_meetin_priorit_fbe104_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingactionitem',
            index=models.Index(fields=['due_date'], name='core_meetin_due_dat_9ec39a_idx'),
        ),
    ]
