# Generated by Django 5.1.7 on 2026-01-09 05:11

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_historicalmeeting_meeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMeetingNote',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('note_type', models.CharField(blank=True, choices=[('note', 'Note'), ('quote', 'Quote')], max_length=255, null=True)),
                ('content', models.TextField()),
                ('datetime_created', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.meeting')),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person')),
            ],
            options={
                'verbose_name': '_Historical Record for MeetingNote',
                'verbose_name_plural': '_Historical Records for MeetingNote',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('note_type', models.CharField(blank=True, choices=[('note', 'Note'), ('quote', 'Quote')], max_length=255, null=True)),
                ('content', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to='core.meeting')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting_notes', to='core.person')),
            ],
            options={
                'verbose_name': 'Meeting Note',
                'verbose_name_plural': 'Meeting Notes',
                'ordering': ['datetime_created', 'id'],
                'indexes': [models.Index(fields=['note_type'], name='core_meetin_note_ty_2f0aac_idx'), models.Index(fields=['datetime_created'], name='core_meetin_datetim_c7db38_idx')],
            },
        ),
    ]
