# Generated by Django 5.1.7 on 2026-01-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_historicalmeetingnote_meetingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='actual_attendees',
            field=models.ManyToManyField(blank=True, related_name='meetings_actually_attended', to='core.person'),
        ),
    ]
