# Generated by Django 5.1.7 on 2026-01-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_meeting_actual_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='badinteraction',
            name='evidence_file',
            field=models.FileField(blank=True, help_text='Evidence file stored in MinIO object storage', null=True, upload_to='bad_interactions/evidence/'),
        ),
        migrations.AddField(
            model_name='badinteraction',
            name='migrated_to_minio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='badinteractionupdate',
            name='attachment_file',
            field=models.FileField(blank=True, help_text='Attachment file stored in MinIO object storage', null=True, upload_to='bad_interactions/updates/'),
        ),
        migrations.AddField(
            model_name='badinteractionupdate',
            name='migrated_to_minio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='File stored in MinIO object storage', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='migrated_to_minio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalbadinteraction',
            name='evidence_file',
            field=models.TextField(blank=True, help_text='Evidence file stored in MinIO object storage', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbadinteraction',
            name='migrated_to_minio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalbadinteractionupdate',
            name='attachment_file',
            field=models.TextField(blank=True, help_text='Attachment file stored in MinIO object storage', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalbadinteractionupdate',
            name='migrated_to_minio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='file',
            field=models.TextField(blank=True, help_text='File stored in MinIO object storage', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='migrated_to_minio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalhrincidentupdate',
            name='attachment_file',
            field=models.TextField(blank=True, help_text='Attachment file stored in MinIO object storage', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalhrincidentupdate',
            name='migrated_to_minio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hrincidentupdate',
            name='attachment_file',
            field=models.FileField(blank=True, help_text='Attachment file stored in MinIO object storage', null=True, upload_to='hr_incidents/updates/'),
        ),
        migrations.AddField(
            model_name='hrincidentupdate',
            name='migrated_to_minio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
