# Generated by Django 5.1.7 on 2026-01-10 03:57

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_badinteraction_evidence_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPasskeyChallenge',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('challenge_type', models.CharField(blank=True, choices=[('registration', 'Registration'), ('authentication', 'Authentication')], max_length=255, null=True)),
                ('challenge', models.TextField()),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(blank=True, default=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '_Historical Record for PasskeyChallenge',
                'verbose_name_plural': '_Historical Records for PasskeyChallenge',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserPasskey',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_id', models.TextField(db_index=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.IntegerField(blank=True, null=True)),
                ('aaguid', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transports', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_eligible', models.BooleanField(blank=True, default=False, null=True)),
                ('backup_state', models.BooleanField(blank=True, default=False, null=True)),
                ('user_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '_Historical Record for UserPasskey',
                'verbose_name_plural': '_Historical Records for UserPasskey',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PasskeyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('challenge_type', models.CharField(blank=True, choices=[('registration', 'Registration'), ('authentication', 'Authentication')], max_length=255, null=True)),
                ('challenge', models.TextField()),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passkey_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passkey Challenge',
                'verbose_name_plural': 'Passkey Challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['challenge', 'challenge_type'], name='core_passke_challen_1853df_idx'), models.Index(fields=['session_key'], name='core_passke_session_c2037f_idx'), models.Index(fields=['-created_at'], name='core_passke_created_e98db9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPasskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_id', models.TextField(unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.IntegerField(blank=True, null=True)),
                ('aaguid', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transports', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_eligible', models.BooleanField(blank=True, default=False, null=True)),
                ('backup_state', models.BooleanField(blank=True, default=False, null=True)),
                ('user_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Passkey',
                'verbose_name_plural': 'User Passkeys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_userpa_user_id_f80e9f_idx'), models.Index(fields=['credential_id'], name='core_userpa_credent_cab4b2_idx')],
            },
        ),
    ]
