# Generated by Django 5.1.7 on 2026-01-10 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_historicalpasskeychallenge_historicaluserpasskey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpasskeychallenge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicaluserpasskey',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicaluserpasskey',
            name='sign_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passkeychallenge',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userpasskey',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userpasskey',
            name='sign_count',
            field=models.IntegerField(default=0),
        ),
    ]
