# Generated by Django 5.1.7 on 2026-01-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_alter_historicalpasskeychallenge_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badinteraction',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='bad_interactions', to='core.document'),
        ),
        migrations.AddField(
            model_name='badinteractionupdate',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='bad_interaction_updates', to='core.document'),
        ),
        migrations.AddField(
            model_name='hrincidentupdate',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='hr_incident_updates', to='core.document'),
        ),
    ]
