from core.views.service_provider_security_requirements_document.service_provider_security_requirements_document_add_view import service_provider_security_requirements_document_add_view
from core.views.service_provider_security_requirements_document.service_provider_security_requirements_document_delete_view import service_provider_security_requirements_document_delete_view
from core.views.service_provider_security_requirements_document.service_provider_security_requirements_document_detail_view import service_provider_security_requirements_document_detail_view
from core.views.service_provider_security_requirements_document.service_provider_security_requirements_document_edit_view import service_provider_security_requirements_document_edit_view
from core.views.service_provider_security_requirements_document.service_provider_security_requirements_document_view import service_provider_security_requirements_document_view

__all__ = [
    'service_provider_security_requirements_document_add_view',
    'service_provider_security_requirements_document_delete_view',
    'service_provider_security_requirements_document_detail_view',
    'service_provider_security_requirements_document_edit_view',
    'service_provider_security_requirements_document_view',
]
