from datetime import datetime, timezone

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt, RGBColor

from core.models.application import Application
from core.models.procedure_step import ProcedureStepType


def set_narrow_margins(document: Document) -> None:
    """Set 0.5 inch margins on all sides with slightly more space for footer."""
    for section in document.sections:
        section.top_margin = Inches(0.5)
        section.bottom_margin = Inches(0.75)
        section.left_margin = Inches(0.5)
        section.right_margin = Inches(0.5)


def add_header_footer(document: Document, title: str) -> None:
    """Add header with title and footer with page numbers."""
    section = document.sections[0]

    # Add header
    header = section.header
    header_para = header.paragraphs[0]
    header_para.text = title
    header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = header_para.runs[0]
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(100, 100, 100)

    # Add footer with page numbers
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_para.add_run()
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(100, 100, 100)

    # Add field for page number
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn

    fldChar1 = OxmlElement('w:fldChar')
    fldChar1.set(qn('w:fldCharType'), 'begin')

    instrText = OxmlElement('w:instrText')
    instrText.set(qn('xml:space'), 'preserve')
    instrText.text = 'PAGE'

    fldChar2 = OxmlElement('w:fldChar')
    fldChar2.set(qn('w:fldCharType'), 'end')

    run._r.append(fldChar1)
    run._r.append(instrText)
    run._r.append(fldChar2)


def add_title_page(document: Document, username: str, total_count: int) -> None:
    """Add title page with metadata."""
    # Title
    title = document.add_heading('Enterprise Applications Export', level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata table
    table = document.add_table(rows=3, cols=2)
    table.style = 'Light Grid Accent 1'

    table.rows[0].cells[0].text = 'Generated By'
    table.rows[0].cells[1].text = username

    table.rows[1].cells[0].text = 'Generated Date'
    now = datetime.now(timezone.utc)
    table.rows[1].cells[1].text = now.strftime('%Y-%m-%d %I:%M %p UTC')

    table.rows[2].cells[0].text = 'Total Applications'
    table.rows[2].cells[1].text = str(total_count)

    # Format table
    for row in table.rows:
        row.cells[0].paragraphs[0].runs[0].bold = True
        for cell in row.cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(9)

    document.add_page_break()


def add_toc_placeholder(document: Document) -> None:
    """Add table of contents placeholder with instructions."""
    document.add_heading('Table of Contents', level=1)

    toc_note = document.add_paragraph()
    run = toc_note.add_run('In Microsoft Word: Right-click here → Update Field → Update entire table')
    run.italic = True
    run.font.size = Pt(9)
    toc_note.alignment = WD_ALIGN_PARAGRAPH.CENTER

    document.add_paragraph()  # Spacing
    document.add_page_break()


def add_application_heading(document: Document, application: Application) -> None:
    """Add H1 heading for application (enables TOC generation)."""
    from core.utilities.get_name_acronym import get_name_acronym

    heading_text = get_name_acronym(acronym=application.acronym, name=application.name)
    heading = document.add_heading(heading_text, level=1)
    heading.runs[0].font.size = Pt(14)


def format_table_cell(cell, text: str, bold: bool = False, font_size: int = 9) -> None:
    """Format table cell with text and styling."""
    cell.text = str(text) if text else ''
    if cell.paragraphs:
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.font.size = Pt(font_size)
                if bold:
                    run.bold = True


def format_list_with_limit(document: Document, items, limit: int = 20, item_format_func=str) -> int:
    """Add bulleted list, limiting to first N items with '... and X more' note.

    Returns the number of items displayed.
    """
    items_list = list(items)
    count = len(items_list)

    for i, item in enumerate(items_list[:limit]):
        para = document.add_paragraph(style='List Bullet')
        run = para.add_run(item_format_func(item))
        run.font.size = Pt(9)

    if count > limit:
        para = document.add_paragraph(style='List Bullet')
        run = para.add_run(f'... and {count - limit} more')
        run.font.size = Pt(9)
        run.italic = True
        run.font.color.rgb = RGBColor(100, 100, 100)

    return min(count, limit)
