# Generated by Django 5.1.7 on 2026-01-12 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('git_lab', '0001_initial'),
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPerformanceIndicatorSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('scrum_capacity_base', models.IntegerField(blank=True, null=True)),
                ('cached_capacity_adjusted', models.IntegerField(blank=True, null=True)),
                ('cached_capacity_base_velocity', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('cached_capacity_per_day', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('cached_commitment_accuracy', models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True)),
                ('number_of_code_lines_added', models.IntegerField(blank=True, null=True)),
                ('number_of_code_lines_removed', models.IntegerField(blank=True, null=True)),
                ('number_of_comments_made', models.IntegerField(blank=True, null=True)),
                ('number_of_context_switches', models.IntegerField(blank=True, null=True)),
                ('number_of_issues_written', models.IntegerField(blank=True, null=True)),
                ('number_of_merge_requests_approved', models.IntegerField(blank=True, null=True)),
                ('number_of_paid_time_off_days', models.IntegerField(blank=True, null=True)),
                ('number_of_story_points_committed_to', models.IntegerField(blank=True, null=True)),
                ('number_of_story_points_delivered', models.IntegerField(blank=True, null=True)),
                ('number_of_threads_made', models.IntegerField(blank=True, null=True)),
                ('git_lab_issues', models.ManyToManyField(blank=True, related_name='kpi_sprints', to='git_lab.gitlabissue')),
                ('git_lab_iterations', models.ManyToManyField(blank=True, related_name='kpi_sprints', to='git_lab.gitlabiteration')),
                ('git_lab_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kpi_sprints', to='git_lab.gitlabuser')),
                ('person_developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.person')),
                ('scrum_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kpi_sprints', to='scrum.scrumsprint')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.sprint')),
            ],
            options={
                'verbose_name': 'Key Performance Indicator (KPI) Sprint',
                'verbose_name_plural': 'Key Performance Indicator (KPI) Sprints',
                'ordering': ['-scrum_sprint__date_end', '-sprint__date_end', '-id'],
            },
        ),
    ]
