# Generated by Django 5.1.6 on 2025-03-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalkeyperformanceindicatorsprint',
            old_name='number_of_code_reviews_submitted',
            new_name='number_of_merge_requests_approved',
        ),
        migrations.RenameField(
            model_name='keyperformanceindicatorsprint',
            old_name='number_of_code_reviews_submitted',
            new_name='number_of_merge_requests_approved',
        ),
    ]
