# Generated by Django 5.1.7 on 2026-01-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyperformanceindicatorsprint',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
