# Generated by Django 5.1.7 on 2026-01-12 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_action_user_of_last_run_and_more'),
        ('git_lab', '0003_alter_gitlabchange_author_and_more'),
        ('kpi', '0002_alter_keyperformanceindicatorsprint_enumeration_attack_uuid'),
        ('scrum', '0003_alter_scrumwish_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyperformanceindicatorsprint',
            name='cached_capacity_base_velocity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='keyperformanceindicatorsprint',
            name='cached_capacity_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='keyperformanceindicatorsprint',
            name='cached_commitment_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='keyperformanceindicatorsprint',
            name='git_lab_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_sprints', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='keyperformanceindicatorsprint',
            name='person_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person'),
        ),
        migrations.AlterField(
            model_name='keyperformanceindicatorsprint',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_sprints', to='scrum.scrumsprint'),
        ),
        migrations.AlterField(
            model_name='keyperformanceindicatorsprint',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sprint'),
        ),
    ]
