# Generated by Django 5.1.6 on 2025-03-05 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_rename_number_of_code_reviews_submitted_historicalkeyperformanceindicatorsprint_number_of_merge_requ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalkeyperformanceindicatorsprint',
            old_name='number_of_threads_resolved',
            new_name='number_of_threads_made',
        ),
        migrations.RenameField(
            model_name='keyperformanceindicatorsprint',
            old_name='number_of_threads_resolved',
            new_name='number_of_threads_made',
        ),
    ]
