# Generated by Django 5.1.7 on 2026-01-11 22:30
#
# IMPORTANT: This migration cleans up Historical model classes after 0002 dropped the tables.
# The tables no longer exist (dropped by 0002_drop_unused_historical_tables),
# so this migration should be FAKE-APPLIED on all systems:
#
#   python manage.py migrate --fake kpi 0003
#
# This migration exists to keep Django's migration state consistent with the code.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_drop_unused_historical_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalKeyPerformanceIndicatorSprint',
        ),
    ]
