# Generated by Django 5.1.7 on 2026-01-13 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_alter_keyperformanceindicatorsprint_cached_capacity_base_velocity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyperformanceindicatorsprint',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
