# Generated by Django 5.1.6 on 2025-03-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_alter_historicalkeyperformanceindicatorsprint_enumeration_attack_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkeyperformanceindicatorsprint',
            name='cached_capacity_base_velocity',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalkeyperformanceindicatorsprint',
            name='cached_commitment_accuracy',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicatorsprint',
            name='cached_capacity_base_velocity',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='keyperformanceindicatorsprint',
            name='cached_commitment_accuracy',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=20, null=True),
        ),
    ]
