# Generated by Django 5.1.6 on 2025-03-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_historicalkeyperformanceindicatorsprint_cached_capacity_base_velocity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyperformanceindicatorsprint',
            options={'ordering': ['-sprint__date_end', '-id']},
        ),
    ]
