# Generated by Django 5.1.6 on 2025-03-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0007_alter_keyperformanceindicatorsprint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalkeyperformanceindicatorsprint',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': '_Historical Record for KeyPerformanceIndicatorSprint', 'verbose_name_plural': '_Historical Records for KeyPerformanceIndicatorSprint'},
        ),
    ]
