# Generated by Django 5.1.6 on 2025-03-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0008_alter_historicalkeyperformanceindicatorsprint_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalkeyperformanceindicatorsprint',
            old_name='capacity_base',
            new_name='scrum_capacity_base',
        ),
        migrations.RenameField(
            model_name='keyperformanceindicatorsprint',
            old_name='capacity_base',
            new_name='scrum_capacity_base',
        ),
    ]
