# Generated by Django 5.1.6 on 2025-03-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0009_rename_capacity_base_historicalkeyperformanceindicatorsprint_scrum_capacity_base_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyperformanceindicatorsprint',
            options={'ordering': ['-sprint__date_end', '-id'], 'verbose_name': 'Key Performance Indicator (KPI) Sprint', 'verbose_name_plural': 'Key Performance Indicator (KPI) Sprints'},
        ),
    ]
