# Generated by Django 5.1.7 on 2025-03-11 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0010_alter_keyperformanceindicatorsprint_options'),
        ('scrum', '0003_historicalscrumsprint_cached_total_number_of_merge_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkeyperformanceindicatorsprint',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scrum.scrumsprint'),
        ),
        migrations.AddField(
            model_name='keyperformanceindicatorsprint',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kpi_sprints', to='scrum.scrumsprint'),
        ),
    ]
