# Generated by Django 5.1.7 on 2025-03-11 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0019_remove_gitlabmergerequest_iteration_and_more'),
        ('kpi', '0011_historicalkeyperformanceindicatorsprint_scrum_sprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkeyperformanceindicatorsprint',
            name='git_lab_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='git_lab.gitlabuser'),
        ),
        migrations.AddField(
            model_name='keyperformanceindicatorsprint',
            name='git_lab_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kpi_sprints', to='git_lab.gitlabuser'),
        ),
    ]
