# Generated by Django 5.1.7 on 2025-11-05 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_application_centralized_logging_status_and_more'),
        ('gitlab_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabsyncuser',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.person'),
        ),
        migrations.AddField(
            model_name='historicalgitlabsyncuser',
            name='person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person'),
        ),
    ]
