# Generated by Django 5.1.7 on 2026-01-12 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_action_user_of_last_run_and_more'),
        ('gitlab_sync', '0002_alter_gitlabsyncartifact_enumeration_attack_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabsyncartifact',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='gitlab_sync.gitlabsyncjob'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncartifact',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncbranch',
            name='can_push',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncbranch',
            name='default',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncbranch',
            name='developers_can_merge',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncbranch',
            name='developers_can_push',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncbranch',
            name='merged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncbranch',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncbranch',
            name='protected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncbranch',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='gitlab_sync.gitlabsyncrepository'),
        ),
        migrations.AlterField(
            model_name='gitlabsynccommit',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits_authored', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsynccommit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsynccommit',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commits', to='gitlab_sync.gitlabsyncrepository'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncepic',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics_authored', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncepic',
            name='confidential',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncepic',
            name='due_date_is_fixed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncepic',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epics', to='gitlab_sync.gitlabsyncgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncepic',
            name='parent_epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_epics', to='gitlab_sync.gitlabsyncepic'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncepic',
            name='start_date_is_fixed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncevent',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_authored', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncissue',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_authored', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncissue',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_closed', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncissue',
            name='confidential',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncissue',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='gitlab_sync.gitlabsyncepic'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncissue',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='gitlab_sync.gitlabsyncgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncissue',
            name='has_tasks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncissue',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='gitlab_sync.gitlabsynciteration'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncissue',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='gitlab_sync.gitlabsyncmilestone'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncissue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsynciteration',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iterations', to='gitlab_sync.gitlabsyncgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncjob',
            name='allow_failure',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncjob',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncjob',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='gitlab_sync.gitlabsyncpipeline'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncjob',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncjob',
            name='queued_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncjob',
            name='tag',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_triggered', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncjobtracker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gitlab_sync_job_trackers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests_authored', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='blocking_discussions_resolved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests_closed', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='draft',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='gitlab_sync.gitlabsyncgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='has_conflicts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='head_pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='gitlab_sync.gitlabsyncpipeline'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='gitlab_sync.gitlabsynciteration'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests_merged', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='gitlab_sync.gitlabsyncmilestone'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='squash',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmilestone',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='gitlab_sync.gitlabsyncgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmilestone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncpipeline',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncpipeline',
            name='merge_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='gitlab_sync.gitlabsyncmergerequest'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncpipeline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncpipeline',
            name='queued_duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncpipeline',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines_triggered', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncproject',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gitlab_sync_projects', to='core.application'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncproject',
            name='archived',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncproject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='gitlab_sync.gitlabsyncgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncrepository',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncsecurityreport',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_reports', to='gitlab_sync.gitlabsyncpipeline'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncsecurityreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_reports', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncsnippet',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippets', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncsnippet',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snippets', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsynctag',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsynctag',
            name='protected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsynctag',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='gitlab_sync.gitlabsyncrepository'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncuser',
            name='bot',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncuser',
            name='locked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncuser',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gitlab_sync_users', to='core.person'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncvulnerability',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities_reported', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncvulnerability',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities_dismissed', to='gitlab_sync.gitlabsyncuser'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncvulnerability',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='gitlab_sync.gitlabsyncproject'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncvulnerability',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities', to='gitlab_sync.gitlabsyncsecurityreport'),
        ),
        migrations.AlterField(
            model_name='gitlabsyncvulnerability',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerabilities_resolved', to='gitlab_sync.gitlabsyncuser'),
        ),
    ]
