# Generated by Django 5.1.7 on 2026-01-13 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_sync', '0003_alter_gitlabsyncartifact_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabsyncartifact',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncbranch',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsynccommit',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncepic',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncevent',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncgroup',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncissue',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsynciteration',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncjob',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncjobtracker',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmergerequest',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncmilestone',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncpipeline',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncproject',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncrepository',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncsecurityreport',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncsnippet',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsynctag',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncuser',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gitlabsyncvulnerability',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
