# Generated by Django 5.1.7 on 2025-11-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_sync', '0003_gitlabsyncjobtracker_historicalgitlabsyncjobtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabsyncjobtracker',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabsyncjobtracker',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=255, null=True),
        ),
    ]
