# Generated by Django 5.1.7 on 2025-11-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_sync', '0004_alter_gitlabsyncjobtracker_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabsyncgroup',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gitlabsyncpipeline',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gitlabsyncproject',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgitlabsyncgroup',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgitlabsyncpipeline',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgitlabsyncproject',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
