# Generated by Django 5.1.7 on 2025-11-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_sync', '0005_gitlabsyncgroup_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabsyncuser',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgitlabsyncuser',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
