# Generated by Django 5.1.7 on 2025-11-05 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_gitlab_sync_skip_group_ids'),
        ('gitlab_sync', '0006_add_user_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabsyncproject',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gitlab_sync_projects', to='core.application'),
        ),
        migrations.AddField(
            model_name='historicalgitlabsyncproject',
            name='application',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.application'),
        ),
    ]
