# Generated by Django 5.1.7 on 2025-11-05 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_sync', '0009_gitlabsyncissue_milestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabsyncissue',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues', to='gitlab_sync.gitlabsynciteration'),
        ),
        migrations.AddField(
            model_name='gitlabsyncmergerequest',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merge_requests', to='gitlab_sync.gitlabsynciteration'),
        ),
        migrations.AddField(
            model_name='historicalgitlabsyncissue',
            name='iteration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gitlab_sync.gitlabsynciteration'),
        ),
        migrations.AddField(
            model_name='historicalgitlabsyncmergerequest',
            name='iteration',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gitlab_sync.gitlabsynciteration'),
        ),
    ]
