# Generated by Django 5.1.6 on 2025-03-08 21:22

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabProject',
            fields=[
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('container_registry_image_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('default_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('http_url_to_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('link_cluster_agents', models.CharField(blank=True, max_length=255, null=True)),
                ('link_events', models.CharField(blank=True, max_length=255, null=True)),
                ('link_issues', models.CharField(blank=True, max_length=255, null=True)),
                ('link_labels', models.CharField(blank=True, max_length=255, null=True)),
                ('link_members', models.CharField(blank=True, max_length=255, null=True)),
                ('link_merge_requests', models.CharField(blank=True, max_length=255, null=True)),
                ('link_repo_branches', models.CharField(blank=True, max_length=255, null=True)),
                ('link_self', models.CharField(blank=True, max_length=255, null=True)),
                ('name_with_namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('open_issues_count', models.IntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('path_with_namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('readme_url', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_url_to_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'GitLab Project',
                'verbose_name_plural': 'GitLab Projects',
                'ordering': ['path_with_namespace'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalGitLabProject',
            fields=[
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('container_registry_image_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('default_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('http_url_to_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(db_index=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('link_cluster_agents', models.CharField(blank=True, max_length=255, null=True)),
                ('link_events', models.CharField(blank=True, max_length=255, null=True)),
                ('link_issues', models.CharField(blank=True, max_length=255, null=True)),
                ('link_labels', models.CharField(blank=True, max_length=255, null=True)),
                ('link_members', models.CharField(blank=True, max_length=255, null=True)),
                ('link_merge_requests', models.CharField(blank=True, max_length=255, null=True)),
                ('link_repo_branches', models.CharField(blank=True, max_length=255, null=True)),
                ('link_self', models.CharField(blank=True, max_length=255, null=True)),
                ('name_with_namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('open_issues_count', models.IntegerField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('path_with_namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('readme_url', models.CharField(blank=True, max_length=255, null=True)),
                ('ssh_url_to_repo', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '_Historical Record for GitLabProject',
                'verbose_name_plural': '_Historical Records for GitLabProject',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
