# Generated by Django 5.1.7 on 2026-01-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabchange',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabdiscussion',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabgroup',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabissue',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabiteration',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabnote',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabproject',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabuser',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabchange',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabdiscussion',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabgroup',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabissue',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabiteration',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabmergerequest',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabnote',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabproject',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabuser',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
