# Generated by Django 5.1.7 on 2026-01-12 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0002_alter_gitlabchange_enumeration_attack_uuid_and_more'),
        ('scrum', '0002_alter_historicalscrumsprint_enumeration_attack_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabchange',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_authored', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabchange',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_closed', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabchange',
            name='draft',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabchange',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='git_lab.gitlabgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabchange',
            name='has_conflicts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabchange',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_merged', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabchange',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='git_lab.gitlabproject'),
        ),
        migrations.AlterField(
            model_name='gitlabchange',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='scrum.scrumsprint'),
        ),
        migrations.AlterField(
            model_name='gitlabdiscussion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='git_lab.gitlabgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabdiscussion',
            name='individual_note',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabdiscussion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='git_lab.gitlabproject'),
        ),
        migrations.AlterField(
            model_name='gitlabdiscussion',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='scrum.scrumsprint'),
        ),
        migrations.AlterField(
            model_name='gitlabdiscussion',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions_started', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabissue',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_authored', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabissue',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_closed', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabissue',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='git_lab.gitlabgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabissue',
            name='has_tasks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabissue',
            name='iteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='git_lab.gitlabiteration'),
        ),
        migrations.AlterField(
            model_name='gitlabissue',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='git_lab.gitlabproject'),
        ),
        migrations.AlterField(
            model_name='gitlabissue',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='scrum.scrumsprint'),
        ),
        migrations.AlterField(
            model_name='gitlabiteration',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iterations', to='git_lab.gitlabgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabiteration',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iterations', to='scrum.scrumsprint'),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests_authored', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='blocking_discussions_resolved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests_closed', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='draft',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='git_lab.gitlabgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='has_conflicts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests_merged', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='git_lab.gitlabproject'),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests', to='scrum.scrumsprint'),
        ),
        migrations.AlterField(
            model_name='gitlabnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_authored', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabnote',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='git_lab.gitlabdiscussion'),
        ),
        migrations.AlterField(
            model_name='gitlabnote',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='git_lab.gitlabgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabnote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='git_lab.gitlabproject'),
        ),
        migrations.AlterField(
            model_name='gitlabnote',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='scrum.scrumsprint'),
        ),
        migrations.AlterField(
            model_name='gitlabnote',
            name='system',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabproject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='git_lab.gitlabgroup'),
        ),
        migrations.AlterField(
            model_name='gitlabproject',
            name='should_skip',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabuser',
            name='locked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabchange',
            name='draft',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabchange',
            name='has_conflicts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabdiscussion',
            name='individual_note',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabissue',
            name='has_tasks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabmergerequest',
            name='blocking_discussions_resolved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabmergerequest',
            name='draft',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabmergerequest',
            name='has_conflicts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabnote',
            name='system',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabproject',
            name='should_skip',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabuser',
            name='locked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
