# Generated by Django 5.1.6 on 2025-03-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0005_gitlabmergerequest_historicalgitlabmergerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='time_stats_human_time_estimate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='time_stats_human_total_time_spent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabmergerequest',
            name='time_stats_human_time_estimate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgitlabmergerequest',
            name='time_stats_human_total_time_spent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
