# Generated by Django 5.1.6 on 2025-03-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0006_alter_gitlabmergerequest_time_stats_human_time_estimate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitlabuser',
            old_name='membership_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='historicalgitlabuser',
            old_name='membership_state',
            new_name='state',
        ),
    ]
