# Generated by Django 5.1.6 on 2025-03-09 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0008_alter_gitlabgroup_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabmergerequest',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='merge_requests_assigned', to='git_lab.gitlabuser'),
        ),
        migrations.AddField(
            model_name='gitlabmergerequest',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merge_requests_authored', to='git_lab.gitlabuser'),
        ),
        migrations.AddField(
            model_name='gitlabmergerequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merge_requests_closed', to='git_lab.gitlabuser'),
        ),
        migrations.AddField(
            model_name='historicalgitlabmergerequest',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='git_lab.gitlabuser'),
        ),
        migrations.AddField(
            model_name='historicalgitlabmergerequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='git_lab.gitlabuser'),
        ),
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='merge_requests_reviewed', to='git_lab.gitlabuser'),
        ),
    ]
