# Generated by Django 5.1.6 on 2025-03-09 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0009_gitlabmergerequest_assignees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabmergerequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merge_requests', to='git_lab.gitlabproject'),
        ),
    ]
