# Generated by Django 5.1.6 on 2025-03-09 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0010_alter_gitlabmergerequest_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitlabproject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='git_lab.gitlabgroup'),
        ),
    ]
