# Generated by Django 5.1.6 on 2025-03-09 04:30

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0011_alter_gitlabproject_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabIssue',
            fields=[
                ('enumeration_attack_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('iid', models.IntegerField(blank=True, null=True)),
                ('references_long', models.CharField(blank=True, max_length=255, null=True)),
                ('references_relative', models.CharField(blank=True, max_length=255, null=True)),
                ('references_short', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('task_completion_status_completed_count', models.IntegerField(blank=True, null=True)),
                ('task_completion_status_count', models.IntegerField(blank=True, null=True)),
                ('time_stats_human_time_estimate', models.CharField(blank=True, max_length=255, null=True)),
                ('time_stats_human_total_time_spent', models.CharField(blank=True, max_length=255, null=True)),
                ('time_stats_time_estimate', models.IntegerField(blank=True, null=True)),
                ('time_stats_total_time_spent', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('blocking_issues_count', models.IntegerField(blank=True, null=True)),
                ('has_tasks', models.BooleanField(blank=True, default=False, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('user_notes_count', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('assignees', models.ManyToManyField(blank=True, related_name='issues_assigned', to='git_lab.gitlabuser')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues_authored', to='git_lab.gitlabuser')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues_closed', to='git_lab.gitlabuser')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues', to='git_lab.gitlabproject')),
            ],
            options={
                'verbose_name': 'GitLab Issue',
                'verbose_name_plural': 'GitLab Issues',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalGitLabIssue',
            fields=[
                ('enumeration_attack_uuid', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(db_index=True)),
                ('web_url', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('iid', models.IntegerField(blank=True, null=True)),
                ('references_long', models.CharField(blank=True, max_length=255, null=True)),
                ('references_relative', models.CharField(blank=True, max_length=255, null=True)),
                ('references_short', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('task_completion_status_completed_count', models.IntegerField(blank=True, null=True)),
                ('task_completion_status_count', models.IntegerField(blank=True, null=True)),
                ('time_stats_human_time_estimate', models.CharField(blank=True, max_length=255, null=True)),
                ('time_stats_human_total_time_spent', models.CharField(blank=True, max_length=255, null=True)),
                ('time_stats_time_estimate', models.IntegerField(blank=True, null=True)),
                ('time_stats_total_time_spent', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('blocking_issues_count', models.IntegerField(blank=True, null=True)),
                ('has_tasks', models.BooleanField(blank=True, default=False, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('user_notes_count', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='git_lab.gitlabuser')),
                ('closed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='git_lab.gitlabuser')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='git_lab.gitlabproject')),
            ],
            options={
                'verbose_name': '_Historical Record for GitLabIssue',
                'verbose_name_plural': '_Historical Records for GitLabIssue',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
