# Generated by Django 5.1.6 on 2025-03-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0013_gitlabissue_link_award_emoji_gitlabissue_link_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitlabissue',
            options={'ordering': ['-references_long'], 'verbose_name': 'GitLab Issue', 'verbose_name_plural': 'GitLab Issues'},
        ),
    ]
