# Generated by Django 5.1.6 on 2025-03-09 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0014_alter_gitlabissue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gitlabissue',
            options={'ordering': ['-id'], 'verbose_name': 'GitLab Issue', 'verbose_name_plural': 'GitLab Issues'},
        ),
    ]
