# Generated by Django 5.1.7 on 2025-03-10 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0018_gitlabmergerequest_iteration_and_more'),
        ('scrum', '0003_historicalscrumsprint_cached_total_number_of_merge_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabmergerequest',
            name='iteration',
        ),
        migrations.RemoveField(
            model_name='historicalgitlabmergerequest',
            name='iteration',
        ),
        migrations.AddField(
            model_name='gitlabmergerequest',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='merge_requests', to='scrum.scrumsprint'),
        ),
        migrations.AddField(
            model_name='historicalgitlabmergerequest',
            name='sprint',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scrum.scrumsprint'),
        ),
    ]
