# Generated by Django 5.1.7 on 2025-03-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0020_gitlabchange_historicalgitlabchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabchange',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalgitlabchange',
            name='name',
        ),
    ]
