# Generated by Django 5.1.7 on 2025-03-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0021_remove_gitlabchange_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabchange',
            name='total_files_changed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgitlabchange',
            name='total_files_changed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
