# Generated by Django 5.1.7 on 2025-03-12 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0023_gitlabchange_total_files_updated_and_more'),
        ('scrum', '0004_historicalscrumsprint_cached_total_number_of_lines_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabchange',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='changes', to='scrum.scrumsprint'),
        ),
        migrations.AddField(
            model_name='historicalgitlabchange',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scrum.scrumsprint'),
        ),
    ]
