# Generated by Django 5.1.7 on 2025-03-12 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0025_gitlabdiscussion_gitlabnote_and_more'),
        ('scrum', '0005_historicalscrumsprint_cached_total_number_of_comments_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabnote',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to='scrum.scrumsprint'),
        ),
        migrations.AddField(
            model_name='historicalgitlabnote',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scrum.scrumsprint'),
        ),
    ]
