# Generated by Django 5.1.7 on 2025-03-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0027_alter_gitlabchange_options_alter_gitlabgroup_options_and_more'),
        ('scrum', '0005_historicalscrumsprint_cached_total_number_of_comments_made_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gitlabiteration',
            old_name='sprint',
            new_name='scrum_sprint',
        ),
        migrations.RenameField(
            model_name='gitlabmergerequest',
            old_name='sprint',
            new_name='scrum_sprint',
        ),
        migrations.RenameField(
            model_name='historicalgitlabiteration',
            old_name='sprint',
            new_name='scrum_sprint',
        ),
        migrations.RenameField(
            model_name='historicalgitlabmergerequest',
            old_name='sprint',
            new_name='scrum_sprint',
        ),
        migrations.AddField(
            model_name='gitlabissue',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues', to='git_lab.gitlabgroup'),
        ),
        migrations.AddField(
            model_name='gitlabissue',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues', to='scrum.scrumsprint'),
        ),
        migrations.AddField(
            model_name='historicalgitlabissue',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='git_lab.gitlabgroup'),
        ),
        migrations.AddField(
            model_name='historicalgitlabissue',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scrum.scrumsprint'),
        ),
    ]
