# Generated by Django 5.1.7 on 2025-03-13 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0028_rename_sprint_gitlabiteration_scrum_sprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabchange',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='changes', to='git_lab.gitlabgroup'),
        ),
        migrations.AddField(
            model_name='historicalgitlabchange',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='git_lab.gitlabgroup'),
        ),
    ]
