# Generated by Django 5.1.7 on 2025-03-13 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0029_gitlabchange_group_historicalgitlabchange_group'),
        ('scrum', '0005_historicalscrumsprint_cached_total_number_of_comments_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabdiscussion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discussions', to='git_lab.gitlabgroup'),
        ),
        migrations.AddField(
            model_name='gitlabdiscussion',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discussions', to='scrum.scrumsprint'),
        ),
        migrations.AddField(
            model_name='gitlabnote',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to='git_lab.gitlabgroup'),
        ),
        migrations.AddField(
            model_name='historicalgitlabdiscussion',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='git_lab.gitlabgroup'),
        ),
        migrations.AddField(
            model_name='historicalgitlabdiscussion',
            name='scrum_sprint',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scrum.scrumsprint'),
        ),
        migrations.AddField(
            model_name='historicalgitlabnote',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='git_lab.gitlabgroup'),
        ),
    ]
