# Generated by Django 5.1.7 on 2025-03-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_lab', '0032_alter_gitlabdiscussion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabproject',
            name='should_skip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalgitlabproject',
            name='should_skip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
