# Generated by Django 5.1.7 on 2025-03-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscrumsprint',
            name='cached_total_number_of_issues',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrumsprint',
            name='cached_total_number_of_issues',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
