# Generated by Django 5.1.7 on 2026-01-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscrumsprint',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalscrumstory',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalscrumwish',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrumsprint',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrumstory',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrumwish',
            name='enumeration_attack_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
