# Generated by Django 5.1.7 on 2025-03-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_historicalscrumsprint_cached_total_number_of_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscrumsprint',
            name='cached_total_number_of_merge_requests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrumsprint',
            name='cached_total_number_of_merge_requests',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
