# Generated by Django 5.1.7 on 2026-01-12 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_action_user_of_last_run_and_more'),
        ('scrum', '0002_alter_historicalscrumsprint_enumeration_attack_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumwish',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.application'),
        ),
        migrations.AlterField(
            model_name='scrumwish',
            name='application_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.applicationgroup'),
        ),
        migrations.AlterField(
            model_name='scrumwish',
            name='person_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person'),
        ),
        migrations.AlterField(
            model_name='scrumwish',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project'),
        ),
    ]
