# Generated by Django 5.1.7 on 2026-01-13 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_alter_scrumwish_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscrumsprint',
            name='enumeration_attack_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalscrumstory',
            name='enumeration_attack_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalscrumwish',
            name='enumeration_attack_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='scrumsprint',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scrumstory',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='scrumwish',
            name='enumeration_attack_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
