# Generated by Django 5.1.7 on 2025-03-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_historicalscrumsprint_cached_total_number_of_lines_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscrumsprint',
            name='cached_total_number_of_comments_made',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrumsprint',
            name='cached_total_number_of_comments_made',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
