# Generated by Django 5.1.7 on 2025-08-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_scrumstory_historicalscrumstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalscrumstory',
            name='cached_total_number_of_comments_made',
        ),
        migrations.RemoveField(
            model_name='historicalscrumstory',
            name='cached_total_number_of_issues',
        ),
        migrations.RemoveField(
            model_name='historicalscrumstory',
            name='cached_total_number_of_lines_added',
        ),
        migrations.RemoveField(
            model_name='historicalscrumstory',
            name='cached_total_number_of_lines_removed',
        ),
        migrations.RemoveField(
            model_name='historicalscrumstory',
            name='cached_total_number_of_merge_requests',
        ),
        migrations.RemoveField(
            model_name='scrumstory',
            name='cached_total_number_of_comments_made',
        ),
        migrations.RemoveField(
            model_name='scrumstory',
            name='cached_total_number_of_issues',
        ),
        migrations.RemoveField(
            model_name='scrumstory',
            name='cached_total_number_of_lines_added',
        ),
        migrations.RemoveField(
            model_name='scrumstory',
            name='cached_total_number_of_lines_removed',
        ),
        migrations.RemoveField(
            model_name='scrumstory',
            name='cached_total_number_of_merge_requests',
        ),
    ]
