ACTION_ITEM_STATUS_OPEN = "open"
ACTION_ITEM_STATUS_IN_PROGRESS = "in_progress"
ACTION_ITEM_STATUS_COMPLETED = "completed"
ACTION_ITEM_STATUS_BLOCKED = "blocked"

ACTION_ITEM_STATUS_CHOICES = [
    (ACTION_ITEM_STATUS_OPEN, "Open"),
    (ACTION_ITEM_STATUS_IN_PROGRESS, "In Progress"),
    (ACTION_ITEM_STATUS_COMPLETED, "Completed"),
    (ACTION_ITEM_STATUS_BLOCKED, "Blocked"),
]
