API_AUTH_TYPE_API_KEY: str = "API Key"
API_AUTH_TYPE_BASIC_AUTH: str = "Basic Auth"
API_AUTH_TYPE_BEARER_TOKEN: str = "Bearer Token"
API_AUTH_TYPE_CUSTOM_HEADERS: str = "Custom Headers"
API_AUTH_TYPE_OAUTH: str = "OAuth"

API_AUTH_TYPE_CHOICES: list[tuple[str, str]] = [
    (API_AUTH_TYPE_API_KEY, API_AUTH_TYPE_API_KEY),
    (API_AUTH_TYPE_BASIC_AUTH, API_AUTH_TYPE_BASIC_AUTH),
    (API_AUTH_TYPE_BEARER_TOKEN, API_AUTH_TYPE_BEARER_TOKEN),
    (API_AUTH_TYPE_CUSTOM_HEADERS, API_AUTH_TYPE_CUSTOM_HEADERS),
    (API_AUTH_TYPE_OAUTH, API_AUTH_TYPE_OAUTH),
]
