API_KEY_LOCATION_HEADER: str = "Header"
API_KEY_LOCATION_QUERY: str = "Query Parameter"

API_KEY_LOCATION_CHOICES: list[tuple[str, str]] = [
    (API_KEY_LOCATION_HEADER, API_KEY_LOCATION_HEADER),
    (API_KEY_LOCATION_QUERY, API_KEY_LOCATION_QUERY),
]
