AUTHORIZATION_TYPE_AD = "Active Directory (AD)"
AUTHORIZATION_TYPE_CUSTOM = "Custom"

AUTHORIZATION_TYPE_CHOICES = [
    (AUTHORIZATION_TYPE_AD, AUTHORIZATION_TYPE_AD),
    (AUTHORIZATION_TYPE_CUSTOM, AUTHORIZATION_TYPE_CUSTOM),
]
