AUTHORIZATION_TYPE_AD: str = "Active Directory (AD)"
AUTHORIZATION_TYPE_CUSTOM: str = "Custom"

AUTHORIZATION_TYPE_CHOICES: list[tuple[str, str]] = [
    (AUTHORIZATION_TYPE_AD, AUTHORIZATION_TYPE_AD),
    (AUTHORIZATION_TYPE_CUSTOM, AUTHORIZATION_TYPE_CUSTOM),
]
