AUTHENTICATION_TYPE_AD = "Active Directory (AD)"
AUTHENTICATION_TYPE_CUSTOM = "Custom"

AUTHENTICATION_TYPE_CHOICES = [
    (AUTHENTICATION_TYPE_AD, AUTHENTICATION_TYPE_AD),
    (AUTHENTICATION_TYPE_CUSTOM, AUTHENTICATION_TYPE_CUSTOM),
]
