BAD_INTERACTION_SEVERITY_LOW = 'LOW'
BAD_INTERACTION_SEVERITY_MEDIUM = 'MEDIUM'
BAD_INTERACTION_SEVERITY_HIGH = 'HIGH'
BAD_INTERACTION_SEVERITY_CRITICAL = 'CRITICAL'

BAD_INTERACTION_SEVERITY_CHOICES = [
    (BAD_INTERACTION_SEVERITY_LOW, 'Low'),
    (BAD_INTERACTION_SEVERITY_MEDIUM, 'Medium'),
    (BAD_INTERACTION_SEVERITY_HIGH, 'High'),
    (BAD_INTERACTION_SEVERITY_CRITICAL, 'Critical'),
]
