CENTRALIZED_LOGGING_STATUS_IMPLEMENTED: str = "Implemented"
CENTRALIZED_LOGGING_STATUS_NOT_IMPLEMENTED: str = "Not Implemented"
CENTRALIZED_LOGGING_STATUS_UNKNOWN: str = "Unknown"

# noinspection DuplicatedCode
CENTRALIZED_LOGGING_STATUS_CHOICES: list[tuple[str, str]] = [
    (CENTRALIZED_LOGGING_STATUS_IMPLEMENTED, CENTRALIZED_LOGGING_STATUS_IMPLEMENTED),
    (CENTRALIZED_LOGGING_STATUS_NOT_IMPLEMENTED, CENTRALIZED_LOGGING_STATUS_NOT_IMPLEMENTED),
    (CENTRALIZED_LOGGING_STATUS_UNKNOWN, CENTRALIZED_LOGGING_STATUS_UNKNOWN),
]
