DATABASE_AUTH_METHOD_API_KEY: str = "API Key"
DATABASE_AUTH_METHOD_CERTIFICATE: str = "Certificate (SSL/TLS)"
DATABASE_AUTH_METHOD_HMAC: str = "HMAC"
DATABASE_AUTH_METHOD_IAM: str = "IAM (AWS)"
DATABASE_AUTH_METHOD_JWT_TOKEN: str = "JWT Token"
DATABASE_AUTH_METHOD_KERBEROS: str = "Kerberos"
DATABASE_AUTH_METHOD_LDAP: str = "LDAP"
DATABASE_AUTH_METHOD_NO_AUTH: str = "No Authentication"
DATABASE_AUTH_METHOD_OAUTH: str = "OAuth"
DATABASE_AUTH_METHOD_SERVICE_PRINCIPAL: str = "Service Principal (Azure)"
DATABASE_AUTH_METHOD_USERNAME_PASSWORD: str = "Username & Password"

DATABASE_AUTH_METHOD_CHOICES: list[tuple[str, str]] = [
    (DATABASE_AUTH_METHOD_API_KEY, DATABASE_AUTH_METHOD_API_KEY),
    (DATABASE_AUTH_METHOD_CERTIFICATE, DATABASE_AUTH_METHOD_CERTIFICATE),
    (DATABASE_AUTH_METHOD_HMAC, DATABASE_AUTH_METHOD_HMAC),
    (DATABASE_AUTH_METHOD_IAM, DATABASE_AUTH_METHOD_IAM),
    (DATABASE_AUTH_METHOD_JWT_TOKEN, DATABASE_AUTH_METHOD_JWT_TOKEN),
    (DATABASE_AUTH_METHOD_KERBEROS, DATABASE_AUTH_METHOD_KERBEROS),
    (DATABASE_AUTH_METHOD_LDAP, DATABASE_AUTH_METHOD_LDAP),
    (DATABASE_AUTH_METHOD_NO_AUTH, DATABASE_AUTH_METHOD_NO_AUTH),
    (DATABASE_AUTH_METHOD_OAUTH, DATABASE_AUTH_METHOD_OAUTH),
    (DATABASE_AUTH_METHOD_SERVICE_PRINCIPAL, DATABASE_AUTH_METHOD_SERVICE_PRINCIPAL),
    (DATABASE_AUTH_METHOD_USERNAME_PASSWORD, DATABASE_AUTH_METHOD_USERNAME_PASSWORD),
]
