DATA_STORAGE_FORM_BLOB: str = "Blob"
DATA_STORAGE_FORM_DOCUMENT: str = "Document"
DATA_STORAGE_FORM_RELATIONAL: str = "Relational"

DATA_STORAGE_FORM_CHOICES: list[tuple[str, str]] = [
    (DATA_STORAGE_FORM_BLOB, DATA_STORAGE_FORM_BLOB),
    (DATA_STORAGE_FORM_DOCUMENT, DATA_STORAGE_FORM_DOCUMENT),
    (DATA_STORAGE_FORM_RELATIONAL, DATA_STORAGE_FORM_RELATIONAL),
]
