DATABASE_CONNECTION_TYPE_DEFAULT: str = "Default (TCP/IP)"
DATABASE_CONNECTION_TYPE_HTTP_HTTPS: str = "HTTP/HTTPS"
DATABASE_CONNECTION_TYPE_IN_MEMORY: str = "In-Memory"
DATABASE_CONNECTION_TYPE_NAMED_PIPE: str = "Named Pipe"
DATABASE_CONNECTION_TYPE_UNIX_SOCKET: str = "Unix Socket"

DATABASE_CONNECTION_TYPE_CHOICES: list[tuple[str, str]] = [
    (DATABASE_CONNECTION_TYPE_DEFAULT, DATABASE_CONNECTION_TYPE_DEFAULT),
    (DATABASE_CONNECTION_TYPE_HTTP_HTTPS, DATABASE_CONNECTION_TYPE_HTTP_HTTPS),
    (DATABASE_CONNECTION_TYPE_IN_MEMORY, DATABASE_CONNECTION_TYPE_IN_MEMORY),
    (DATABASE_CONNECTION_TYPE_NAMED_PIPE, DATABASE_CONNECTION_TYPE_NAMED_PIPE),
    (DATABASE_CONNECTION_TYPE_UNIX_SOCKET, DATABASE_CONNECTION_TYPE_UNIX_SOCKET),
]
