DATABASE_FLAVOR_MARIADB = "MariaDB"
DATABASE_FLAVOR_POSTGRESQL = "PostgreSQL"

DATABASE_FLAVOR_CHOICES = [
    (DATABASE_FLAVOR_MARIADB, DATABASE_FLAVOR_MARIADB),
    (DATABASE_FLAVOR_POSTGRESQL, DATABASE_FLAVOR_POSTGRESQL),
]
