DATABASE_FLAVOR_AZURE_BLOB_STORAGE: str = "Azure Blob Storage"
DATABASE_FLAVOR_COSMOSDB: str = "CosmosDB"
DATABASE_FLAVOR_MARIADB: str = "MariaDB"
DATABASE_FLAVOR_MINIO: str = "MinIO"
DATABASE_FLAVOR_MONGODB: str = "MongoDB"
DATABASE_FLAVOR_POSTGRESQL: str = "PostgreSQL"
DATABASE_FLAVOR_SQLITE: str = "SQLite"

DATABASE_FLAVOR_CHOICES: list[tuple[str, str]] = [
    (DATABASE_FLAVOR_AZURE_BLOB_STORAGE, DATABASE_FLAVOR_AZURE_BLOB_STORAGE),
    (DATABASE_FLAVOR_COSMOSDB, DATABASE_FLAVOR_COSMOSDB),
    (DATABASE_FLAVOR_MARIADB, DATABASE_FLAVOR_MARIADB),
    (DATABASE_FLAVOR_MINIO, DATABASE_FLAVOR_MINIO),
    (DATABASE_FLAVOR_MONGODB, DATABASE_FLAVOR_MONGODB),
    (DATABASE_FLAVOR_POSTGRESQL, DATABASE_FLAVOR_POSTGRESQL),
    (DATABASE_FLAVOR_SQLITE, DATABASE_FLAVOR_SQLITE),
]
