DATABASE_TYPE_BLOB: str = "Blob"
DATABASE_TYPE_DOCUMENT: str = "Document"
DATABASE_TYPE_RELATIONAL: str = "Relational"

DATABASE_TYPE_CHOICES: list[tuple[str, str]] = [
    (DATABASE_TYPE_BLOB, DATABASE_TYPE_BLOB),
    (DATABASE_TYPE_DOCUMENT, DATABASE_TYPE_DOCUMENT),
    (DATABASE_TYPE_RELATIONAL, DATABASE_TYPE_RELATIONAL),
]
