DATABASE_TYPE_BLOB = "Blob"
DATABASE_TYPE_DOCUMENT = "Document"
DATABASE_TYPE_RELATIONAL = "Relational"

DATABASE_TYPE_CHOICES = [
    (DATABASE_TYPE_BLOB, DATABASE_TYPE_BLOB),
    (DATABASE_TYPE_DOCUMENT, DATABASE_TYPE_DOCUMENT),
    (DATABASE_TYPE_RELATIONAL, DATABASE_TYPE_RELATIONAL),
]
