DATABASE_FLAVOR_MARIADB: str = "MariaDB"
DATABASE_FLAVOR_POSTGRESQL: str = "PostgreSQL"

DATABASE_FLAVOR_CHOICES: list[tuple[str, str]] = [
    (DATABASE_FLAVOR_MARIADB, DATABASE_FLAVOR_MARIADB),
    (DATABASE_FLAVOR_POSTGRESQL, DATABASE_FLAVOR_POSTGRESQL),
]
