DEPENDENCY_TYPE_CHOICES_BINARY: str = "Binary"
DEPENDENCY_TYPE_CHOICES_FRAMEWORK: str = "Framework"
DEPENDENCY_TYPE_CHOICES_LANGUAGE: str = "Language"
DEPENDENCY_TYPE_CHOICES_PACKAGE: str = "Package"
DEPENDENCY_TYPE_CHOICES_PROTOCOL: str = "Protocol"
DEPENDENCY_TYPE_CHOICES_STANDARD: str = "Standard"

DEPENDENCY_TYPE_CHOICES: list[tuple[str, str]] = [
    (DEPENDENCY_TYPE_CHOICES_BINARY, DEPENDENCY_TYPE_CHOICES_BINARY),
    (DEPENDENCY_TYPE_CHOICES_FRAMEWORK, DEPENDENCY_TYPE_CHOICES_FRAMEWORK),
    (DEPENDENCY_TYPE_CHOICES_LANGUAGE, DEPENDENCY_TYPE_CHOICES_LANGUAGE),
    (DEPENDENCY_TYPE_CHOICES_PACKAGE, DEPENDENCY_TYPE_CHOICES_PACKAGE),
    (DEPENDENCY_TYPE_CHOICES_PROTOCOL, DEPENDENCY_TYPE_CHOICES_PROTOCOL),
    (DEPENDENCY_TYPE_CHOICES_STANDARD, DEPENDENCY_TYPE_CHOICES_STANDARD),
]
