DEPENDENCY_TYPE_CHOICES_BINARY = "Binary"
DEPENDENCY_TYPE_CHOICES_FRAMEWORK = "Framework"
DEPENDENCY_TYPE_CHOICES_LANGUAGE = "Language"
DEPENDENCY_TYPE_CHOICES_PACKAGE = "Package"
DEPENDENCY_TYPE_CHOICES_PROTOCOL = "Protocol"
DEPENDENCY_TYPE_CHOICES_STANDARD = "Standard"

DEPENDENCY_TYPE_CHOICES: list[tuple[str, str]] = [
    (DEPENDENCY_TYPE_CHOICES_BINARY, DEPENDENCY_TYPE_CHOICES_BINARY),
    (DEPENDENCY_TYPE_CHOICES_FRAMEWORK, DEPENDENCY_TYPE_CHOICES_FRAMEWORK),
    (DEPENDENCY_TYPE_CHOICES_LANGUAGE, DEPENDENCY_TYPE_CHOICES_LANGUAGE),
    (DEPENDENCY_TYPE_CHOICES_PACKAGE, DEPENDENCY_TYPE_CHOICES_PACKAGE),
    (DEPENDENCY_TYPE_CHOICES_PROTOCOL, DEPENDENCY_TYPE_CHOICES_PROTOCOL),
    (DEPENDENCY_TYPE_CHOICES_STANDARD, DEPENDENCY_TYPE_CHOICES_STANDARD),
]
