DEPLOYMENT_MEDIUM_CLOUD_AKS = "Cloud - Azure Kubernetes Service (AKS)"
DEPLOYMENT_MEDIUM_CLOUD_DIVIO = "Cloud - Divio"
DEPLOYMENT_MEDIUM_ON_PREMISES_IIS = "On-Premises - Windows Internet Information Services (IIS)"
DEPLOYMENT_MEDIUM_ON_PREMISES_LINUX = "On-Premises - Debian Linux"

DEPLOYMENT_MEDIUM_CHOICES = [
    (DEPLOYMENT_MEDIUM_CLOUD_AKS, DEPLOYMENT_MEDIUM_CLOUD_AKS),
    (DEPLOYMENT_MEDIUM_CLOUD_DIVIO, DEPLOYMENT_MEDIUM_CLOUD_DIVIO),
    (DEPLOYMENT_MEDIUM_ON_PREMISES_IIS, DEPLOYMENT_MEDIUM_ON_PREMISES_IIS),
    (DEPLOYMENT_MEDIUM_ON_PREMISES_LINUX, DEPLOYMENT_MEDIUM_ON_PREMISES_LINUX),
]
