DEPLOYMENT_MEDIUM_CLOUD_AKS: str = "Cloud - Azure Kubernetes Service (AKS)"
DEPLOYMENT_MEDIUM_CLOUD_DIVIO: str = "Cloud - Divio"
DEPLOYMENT_MEDIUM_ON_PREMISES_IIS: str = "On-Premises - Windows Internet Information Services (IIS)"
DEPLOYMENT_MEDIUM_ON_PREMISES_LINUX: str = "On-Premises - Debian Linux"

DEPLOYMENT_MEDIUM_CHOICES: list[tuple[str, str]] = [
    (DEPLOYMENT_MEDIUM_CLOUD_AKS, DEPLOYMENT_MEDIUM_CLOUD_AKS),
    (DEPLOYMENT_MEDIUM_CLOUD_DIVIO, DEPLOYMENT_MEDIUM_CLOUD_DIVIO),
    (DEPLOYMENT_MEDIUM_ON_PREMISES_IIS, DEPLOYMENT_MEDIUM_ON_PREMISES_IIS),
    (DEPLOYMENT_MEDIUM_ON_PREMISES_LINUX, DEPLOYMENT_MEDIUM_ON_PREMISES_LINUX),
]
