ENVIRONMENT_DEVELOPMENT: str = "Development"
ENVIRONMENT_LOCAL: str = "Local"
ENVIRONMENT_PRODUCTION: str = "Production"
ENVIRONMENT_STAGING: str = "Staging"

ENVIRONMENT_CHOICES: list[tuple[str, str]] = [
    (ENVIRONMENT_DEVELOPMENT, ENVIRONMENT_DEVELOPMENT),
    (ENVIRONMENT_LOCAL, ENVIRONMENT_LOCAL),
    (ENVIRONMENT_PRODUCTION, ENVIRONMENT_PRODUCTION),
    (ENVIRONMENT_STAGING, ENVIRONMENT_STAGING),
]
