ENVIRONMENT_DEVELOPMENT: str = "Development"
ENVIRONMENT_LOCAL: str = "Local"
ENVIRONMENT_LOCAL_DOCKER: str = "Local Docker"
ENVIRONMENT_LOCAL_DOCKER_COMPOSE: str = "Local Docker Compose"
ENVIRONMENT_PRODUCTION: str = "Production"
ENVIRONMENT_PRODUCTION_EXTERNAL: str = "Production External"
ENVIRONMENT_STAGING: str = "Staging"

ENVIRONMENT_CHOICES: list[tuple[str, str]] = [
    (ENVIRONMENT_DEVELOPMENT, ENVIRONMENT_DEVELOPMENT),
    (ENVIRONMENT_LOCAL, ENVIRONMENT_LOCAL),
    (ENVIRONMENT_LOCAL_DOCKER, ENVIRONMENT_LOCAL_DOCKER),
    (ENVIRONMENT_LOCAL_DOCKER_COMPOSE, ENVIRONMENT_LOCAL_DOCKER_COMPOSE),
    (ENVIRONMENT_PRODUCTION, ENVIRONMENT_PRODUCTION),
    (ENVIRONMENT_PRODUCTION_EXTERNAL, ENVIRONMENT_PRODUCTION_EXTERNAL),
    (ENVIRONMENT_STAGING, ENVIRONMENT_STAGING),
]
