GIT_LAB_API_VERSION_FOUR: str = "4"
GIT_LAB_API_VERSION_FIVE: str = "5"

GIT_LAB_API_VERSION_CHOICES: list[tuple[str, str]] = [
    (GIT_LAB_API_VERSION_FOUR, GIT_LAB_API_VERSION_FOUR),
    (GIT_LAB_API_VERSION_FIVE, GIT_LAB_API_VERSION_FIVE),
]
