HR_INCIDENT_STATUS_OPEN = 'OPEN'
HR_INCIDENT_STATUS_IN_REVIEW = 'IN_REVIEW'
HR_INCIDENT_STATUS_RESOLVED = 'RESOLVED'
HR_INCIDENT_STATUS_CLOSED = 'CLOSED'

HR_INCIDENT_STATUS_CHOICES = [
    (HR_INCIDENT_STATUS_OPEN, 'Open'),
    (HR_INCIDENT_STATUS_IN_REVIEW, 'In Review'),
    (HR_INCIDENT_STATUS_RESOLVED, 'Resolved'),
    (HR_INCIDENT_STATUS_CLOSED, 'Closed'),
]
