HTTP_METHOD_GET: str = "GET"
HTTP_METHOD_POST: str = "POST"
HTTP_METHOD_PUT: str = "PUT"
HTTP_METHOD_PATCH: str = "PATCH"
HTTP_METHOD_DELETE: str = "DELETE"
HTTP_METHOD_HEAD: str = "HEAD"
HTTP_METHOD_OPTIONS: str = "OPTIONS"

HTTP_METHOD_CHOICES: list[tuple[str, str]] = [
    (HTTP_METHOD_DELETE, HTTP_METHOD_DELETE),
    (HTTP_METHOD_GET, HTTP_METHOD_GET),
    (HTTP_METHOD_HEAD, HTTP_METHOD_HEAD),
    (HTTP_METHOD_OPTIONS, HTTP_METHOD_OPTIONS),
    (HTTP_METHOD_PATCH, HTTP_METHOD_PATCH),
    (HTTP_METHOD_POST, HTTP_METHOD_POST),
    (HTTP_METHOD_PUT, HTTP_METHOD_PUT),
]
