IT_DEVOPS_REQUEST_STATUS_DRAFT: str = "draft"
IT_DEVOPS_REQUEST_STATUS_SUBMITTED: str = "submitted"
IT_DEVOPS_REQUEST_STATUS_IN_PROGRESS: str = "in_progress"
IT_DEVOPS_REQUEST_STATUS_COMPLETED: str = "completed"
IT_DEVOPS_REQUEST_STATUS_CANCELLED: str = "cancelled"

IT_DEVOPS_REQUEST_STATUS_CHOICES: list[tuple[str, str]] = [
    (IT_DEVOPS_REQUEST_STATUS_DRAFT, "Draft"),
    (IT_DEVOPS_REQUEST_STATUS_SUBMITTED, "Submitted"),
    (IT_DEVOPS_REQUEST_STATUS_IN_PROGRESS, "In Progress"),
    (IT_DEVOPS_REQUEST_STATUS_COMPLETED, "Completed"),
    (IT_DEVOPS_REQUEST_STATUS_CANCELLED, "Cancelled"),
]
