JOB_TITLE_DEVELOPER: str = "Developer"
JOB_TITLE_DIRECTOR: str = "Director"
JOB_TITLE_LEAD_DEVELOPER: str = "Lead Developer"
JOB_TITLE_LEAD_SOFTWARE_ARCHITECT: str = "Lead Software Architect"
JOB_TITLE_MANAGER: str = "Manager"
JOB_TITLE_PRODUCT_PARTNER: str = "Partner"
JOB_TITLE_PRODUCT_MANAGER: str = "Product Manager"
JOB_TITLE_PRODUCT_OWNER: str = "Product Owner"
JOB_TITLE_PROJECT_MANAGER: str = "Project Manager"
JOB_TITLE_SCRUM_MASTER: str = "Scrum Master"
JOB_TITLE_SOFTWARE_ARCHITECT: str = "Software Architect"
JOB_TITLE_SOFTWARE_SUPPORT_SPECIALIST: str = "Software Support Specialist"

# noinspection DuplicatedCode
JOB_TITLE_CHOICES: list[tuple[str, str]] = [
    (JOB_TITLE_DEVELOPER, JOB_TITLE_DEVELOPER),
    (JOB_TITLE_DIRECTOR, JOB_TITLE_DIRECTOR),
    (JOB_TITLE_LEAD_DEVELOPER, JOB_TITLE_LEAD_DEVELOPER),
    (JOB_TITLE_LEAD_SOFTWARE_ARCHITECT, JOB_TITLE_LEAD_SOFTWARE_ARCHITECT),
    (JOB_TITLE_MANAGER, JOB_TITLE_MANAGER),
    (JOB_TITLE_PRODUCT_PARTNER, JOB_TITLE_PRODUCT_PARTNER),
    (JOB_TITLE_PRODUCT_MANAGER, JOB_TITLE_PRODUCT_MANAGER),
    (JOB_TITLE_PRODUCT_OWNER, JOB_TITLE_PRODUCT_OWNER),
    (JOB_TITLE_PROJECT_MANAGER, JOB_TITLE_PROJECT_MANAGER),
    (JOB_TITLE_SCRUM_MASTER, JOB_TITLE_SCRUM_MASTER),
    (JOB_TITLE_SOFTWARE_ARCHITECT, JOB_TITLE_SOFTWARE_ARCHITECT),
    (JOB_TITLE_SOFTWARE_SUPPORT_SPECIALIST, JOB_TITLE_SOFTWARE_SUPPORT_SPECIALIST),
]
