JOB_TITLE_DEVELOPER = "Developer"
JOB_TITLE_LEAD_DEVELOPER = "Lead Developer"
JOB_TITLE_LEAD_SOFTWARE_ARCHITECT = "Lead Software Architect"
JOB_TITLE_MANAGER = "Manager"
JOB_TITLE_PRODUCT_MANAGER = "Product Manager"
JOB_TITLE_PRODUCT_OWNER = "Product Owner"
JOB_TITLE_PROJECT_MANAGER = "Project Manager"
JOB_TITLE_SCRUM_MASTER = "Scrum Master"
JOB_TITLE_SOFTWARE_ARCHITECT = "Software Architect"
JOB_TITLE_SOFTWARE_SUPPORT_SPECIALIST = "Software Support Specialist"

JOB_TITLE_CHOICES = [
    (JOB_TITLE_DEVELOPER, JOB_TITLE_DEVELOPER),
    (JOB_TITLE_LEAD_DEVELOPER, JOB_TITLE_LEAD_DEVELOPER),
    (JOB_TITLE_LEAD_SOFTWARE_ARCHITECT, JOB_TITLE_LEAD_SOFTWARE_ARCHITECT),
    (JOB_TITLE_MANAGER, JOB_TITLE_MANAGER),
    (JOB_TITLE_PRODUCT_MANAGER, JOB_TITLE_PRODUCT_MANAGER),
    (JOB_TITLE_PRODUCT_OWNER, JOB_TITLE_PRODUCT_OWNER),
    (JOB_TITLE_PROJECT_MANAGER, JOB_TITLE_PROJECT_MANAGER),
    (JOB_TITLE_SCRUM_MASTER, JOB_TITLE_SCRUM_MASTER),
    (JOB_TITLE_SOFTWARE_ARCHITECT, JOB_TITLE_SOFTWARE_ARCHITECT),
    (JOB_TITLE_SOFTWARE_SUPPORT_SPECIALIST, JOB_TITLE_SOFTWARE_SUPPORT_SPECIALIST),
]
