JOB_LEVEL_JUNIOR = "Junior"
JOB_LEVEL_MID_LEVEL = "Mid-Level"
JOB_LEVEL_SENIOR = "Senior"

JOB_LEVEL_CHOICES = [
    (JOB_LEVEL_JUNIOR, JOB_LEVEL_JUNIOR),
    (JOB_LEVEL_MID_LEVEL, JOB_LEVEL_MID_LEVEL),
    (JOB_LEVEL_SENIOR, JOB_LEVEL_SENIOR),
]
