LIFECYCLE_ACTIVE = "Active"
LIFECYCLE_APPROVAL = "Awaiting Approval"
LIFECYCLE_DEPRECATED = "Deprecated"
LIFECYCLE_DEVELOPMENT = "In Development"
LIFECYCLE_HYPER_CARE = "Hyper Care"
LIFECYCLE_IDEA = "Idea Submission"
LIFECYCLE_IN_DEPRECATION = "In Deprecation Period"
LIFECYCLE_LIMITED_SUPPORT = "Limited Support"
LIFECYCLE_PLANNING = "In Planning"
LIFECYCLE_REJECTED = "Approval Rejected"

LIFECYCLE_CHOICES = [
    (LIFECYCLE_ACTIVE, LIFECYCLE_ACTIVE),
    (LIFECYCLE_APPROVAL, LIFECYCLE_APPROVAL),
    (LIFECYCLE_DEPRECATED, LIFECYCLE_DEPRECATED),
    (LIFECYCLE_DEVELOPMENT, LIFECYCLE_DEVELOPMENT),
    (LIFECYCLE_HYPER_CARE, LIFECYCLE_HYPER_CARE),
    (LIFECYCLE_IDEA, LIFECYCLE_IDEA),
    (LIFECYCLE_IN_DEPRECATION, LIFECYCLE_IN_DEPRECATION),
    (LIFECYCLE_LIMITED_SUPPORT, LIFECYCLE_LIMITED_SUPPORT),
    (LIFECYCLE_PLANNING, LIFECYCLE_PLANNING),
    (LIFECYCLE_REJECTED, LIFECYCLE_REJECTED),
]
