MAINTENANCE_SEVERITY_CRITICAL = "critical"
MAINTENANCE_SEVERITY_HIGH = "high"
MAINTENANCE_SEVERITY_MEDIUM = "medium"
MAINTENANCE_SEVERITY_LOW = "low"

MAINTENANCE_SEVERITY_CHOICES = [
    (MAINTENANCE_SEVERITY_CRITICAL, "Critical"),
    (MAINTENANCE_SEVERITY_HIGH, "High"),
    (MAINTENANCE_SEVERITY_MEDIUM, "Medium"),
    (MAINTENANCE_SEVERITY_LOW, "Low"),
]
