MAINTENANCE_STATUS_PLANNED = "planned"
MAINTENANCE_STATUS_IN_PROGRESS = "in_progress"
MAINTENANCE_STATUS_COMPLETED = "completed"
MAINTENANCE_STATUS_CANCELLED = "cancelled"

MAINTENANCE_STATUS_CHOICES = [
    (MAINTENANCE_STATUS_PLANNED, "Planned"),
    (MAINTENANCE_STATUS_IN_PROGRESS, "In Progress"),
    (MAINTENANCE_STATUS_COMPLETED, "Completed"),
    (MAINTENANCE_STATUS_CANCELLED, "Cancelled"),
]
