MEETING_STATUS_SCHEDULED = "scheduled"
MEETING_STATUS_IN_PROGRESS = "in_progress"
MEETING_STATUS_COMPLETED = "completed"
MEETING_STATUS_CANCELLED = "cancelled"

MEETING_STATUS_CHOICES = [
    (MEETING_STATUS_SCHEDULED, "Scheduled"),
    (MEETING_STATUS_IN_PROGRESS, "In Progress"),
    (MEETING_STATUS_COMPLETED, "Completed"),
    (MEETING_STATUS_CANCELLED, "Cancelled"),
]
