PIPELINE_STATUS_FAILING: str = "Failing"
PIPELINE_STATUS_PASSING: str = "Passing"
PIPELINE_STATUS_UNKNOWN: str = "Unknown"

# noinspection DuplicatedCode
PIPELINE_STATUS_CHOICES: list[tuple[str, str]] = [
    (PIPELINE_STATUS_FAILING, PIPELINE_STATUS_FAILING),
    (PIPELINE_STATUS_PASSING, PIPELINE_STATUS_PASSING),
    (PIPELINE_STATUS_UNKNOWN, PIPELINE_STATUS_UNKNOWN),
]
