PLATFORM_TARGET_BACKGROUND_TASK: str = "Background Task"
PLATFORM_TARGET_CHROME_PLUGIN: str = "Chrome Plugin"
PLATFORM_TARGET_IOS: str = "IOS"
PLATFORM_TARGET_MICROSOFT_EXCEL: str = "Microsoft Excel"
PLATFORM_TARGET_MICROSOFT_EXCEL_VBA: str = "Microsoft Excel + Visual Basic for Applications"
PLATFORM_TARGET_MICROSOFT_WORD: str = "Microsoft Word"
PLATFORM_TARGET_WEB: str = "WEB"

PLATFORM_TARGET_CHOICES: list[tuple[str, str]] = [
    (PLATFORM_TARGET_BACKGROUND_TASK, PLATFORM_TARGET_BACKGROUND_TASK),
    (PLATFORM_TARGET_CHROME_PLUGIN, PLATFORM_TARGET_CHROME_PLUGIN),
    (PLATFORM_TARGET_IOS, PLATFORM_TARGET_IOS),
    (PLATFORM_TARGET_MICROSOFT_EXCEL, PLATFORM_TARGET_MICROSOFT_EXCEL),
    (PLATFORM_TARGET_MICROSOFT_EXCEL_VBA, PLATFORM_TARGET_MICROSOFT_EXCEL_VBA),
    (PLATFORM_TARGET_MICROSOFT_WORD, PLATFORM_TARGET_MICROSOFT_WORD),
    (PLATFORM_TARGET_WEB, PLATFORM_TARGET_WEB),
]
