PLATFORM_BACKGROUND_TASK: str = "Background Task"
PLATFORM_CHROME_PLUGIN: str = "Chrome Plugin"
PLATFORM_IOS: str = "IOS"
PLATFORM_MICROSOFT_EXCEL: str = "Microsoft Excel"
PLATFORM_MICROSOFT_EXCEL_VBA: str = "Microsoft Excel + Visual Basic for Applications"
PLATFORM_MICROSOFT_WORD: str = "Microsoft Word"
PLATFORM_WEB: str = "WEB"

PLATFORM_CHOICES: list[tuple[str, str]] = [
    (PLATFORM_BACKGROUND_TASK, PLATFORM_BACKGROUND_TASK),
    (PLATFORM_CHROME_PLUGIN, PLATFORM_CHROME_PLUGIN),
    (PLATFORM_IOS, PLATFORM_IOS),
    (PLATFORM_MICROSOFT_EXCEL, PLATFORM_MICROSOFT_EXCEL),
    (PLATFORM_MICROSOFT_EXCEL_VBA, PLATFORM_MICROSOFT_EXCEL_VBA),
    (PLATFORM_MICROSOFT_WORD, PLATFORM_MICROSOFT_WORD),
    (PLATFORM_WEB, PLATFORM_WEB),
]
