PLATFORM_BACKGROUND_TASK = "Background Task"
PLATFORM_CHROME_PLUGIN = "Chrome Plugin"
PLATFORM_IOS = "IOS"
PLATFORM_MICROSOFT_EXCEL = "Microsoft Excel"
PLATFORM_MICROSOFT_EXCEL_VBA = "Microsoft Excel + Visual Basic for Applications"
PLATFORM_MICROSOFT_WORD = "Microsoft Word"
PLATFORM_WEB = "WEB"

PLATFORM_CHOICES = [
    (PLATFORM_BACKGROUND_TASK, PLATFORM_BACKGROUND_TASK),
    (PLATFORM_CHROME_PLUGIN, PLATFORM_CHROME_PLUGIN),
    (PLATFORM_IOS, PLATFORM_IOS),
    (PLATFORM_MICROSOFT_EXCEL, PLATFORM_MICROSOFT_EXCEL),
    (PLATFORM_MICROSOFT_EXCEL_VBA, PLATFORM_MICROSOFT_EXCEL_VBA),
    (PLATFORM_MICROSOFT_WORD, PLATFORM_MICROSOFT_WORD),
    (PLATFORM_WEB, PLATFORM_WEB),
]
