PROGRAMING_CONCEPT_BINARY: str = "Binary"
PROGRAMING_CONCEPT_FRAMEWORK: str = "Framework"
PROGRAMING_CONCEPT_LANGUAGE: str = "Language"
PROGRAMING_CONCEPT_PACKAGE: str = "Package"
PROGRAMING_CONCEPT_PROTOCOL: str = "Protocol"
PROGRAMING_CONCEPT_STANDARD: str = "Standard"

PROGRAMING_CONCEPT_CHOICES: list[tuple[str, str]] = [
    (PROGRAMING_CONCEPT_BINARY, PROGRAMING_CONCEPT_BINARY),
    (PROGRAMING_CONCEPT_FRAMEWORK, PROGRAMING_CONCEPT_FRAMEWORK),
    (PROGRAMING_CONCEPT_LANGUAGE, PROGRAMING_CONCEPT_LANGUAGE),
    (PROGRAMING_CONCEPT_PACKAGE, PROGRAMING_CONCEPT_PACKAGE),
    (PROGRAMING_CONCEPT_PROTOCOL, PROGRAMING_CONCEPT_PROTOCOL),
    (PROGRAMING_CONCEPT_STANDARD, PROGRAMING_CONCEPT_STANDARD),
]
