SIGN_OFF_APPROVED = "Approved"
SIGN_OFF_DENIED = "Denied"
SIGN_OFF_PENDING = "Pending"

SIGN_OFF_CHOICES = [
    (SIGN_OFF_APPROVED, SIGN_OFF_APPROVED),
    (SIGN_OFF_DENIED, SIGN_OFF_DENIED),
    (SIGN_OFF_PENDING, SIGN_OFF_PENDING),
]
