SSL_SUPPORT_NOT_SUPPORTED: str = "Not Supported"
SSL_SUPPORT_OPTIONAL: str = "Optional"
SSL_SUPPORT_PREFERRED: str = "Preferred"
SSL_SUPPORT_REQUIRED: str = "Required"

SSL_SUPPORT_CHOICES: list[tuple[str, str]] = [
    (SSL_SUPPORT_NOT_SUPPORTED, SSL_SUPPORT_NOT_SUPPORTED),
    (SSL_SUPPORT_OPTIONAL, SSL_SUPPORT_OPTIONAL),
    (SSL_SUPPORT_PREFERRED, SSL_SUPPORT_PREFERRED),
    (SSL_SUPPORT_REQUIRED, SSL_SUPPORT_REQUIRED),
]
