from datetime import datetime, timezone

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

from core.models.recommendation import (
    RECOMMENDATION_PRIORITY_HIGH,
    RECOMMENDATION_PRIORITY_LOW,
    RECOMMENDATION_PRIORITY_MEDIUM,
    Recommendation,
)
from core.views.application.utilities.application_docx_helpers import (
    add_header_footer as _add_header_footer,
    add_toc_placeholder as _add_toc_placeholder,
    set_narrow_margins as _set_narrow_margins,
)


def set_narrow_margins(document: Document) -> None:
    """Reuse application helper for narrow margins."""
    _set_narrow_margins(document)


def add_header_footer(document: Document, title: str, person_name: str, date_str: str) -> None:
    """Add custom header with person (left), title (center), date (right) and footer with page numbers."""
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml import OxmlElement
    from docx.oxml.ns import qn
    from docx.shared import Pt, RGBColor

    section = document.sections[0]

    # Add header with three parts
    header = section.header
    header_para = header.paragraphs[0]

    # Clear any existing content
    header_para.clear()

    # Add person name (left)
    run_left = header_para.add_run(person_name)
    run_left.font.size = Pt(9)
    run_left.font.color.rgb = RGBColor(100, 100, 100)

    # Add tab to center
    header_para.add_run("\t")

    # Add title (center)
    run_center = header_para.add_run(title)
    run_center.font.size = Pt(9)
    run_center.font.color.rgb = RGBColor(100, 100, 100)
    run_center.bold = True

    # Add tab to right
    header_para.add_run("\t")

    # Add date (right)
    run_right = header_para.add_run(date_str)
    run_right.font.size = Pt(9)
    run_right.font.color.rgb = RGBColor(100, 100, 100)

    # Set tab stops for left-center-right alignment
    from docx.shared import Inches
    from docx.enum.text import WD_TAB_ALIGNMENT

    tab_stops = header_para.paragraph_format.tab_stops
    tab_stops.add_tab_stop(Inches(3.5), WD_TAB_ALIGNMENT.CENTER)
    tab_stops.add_tab_stop(Inches(7.0), WD_TAB_ALIGNMENT.RIGHT)

    # Add footer with page numbers
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer_para.add_run()
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(100, 100, 100)

    # Add field for page number
    fldChar1 = OxmlElement("w:fldChar")
    fldChar1.set(qn("w:fldCharType"), "begin")

    instrText = OxmlElement("w:instrText")
    instrText.set(qn("xml:space"), "preserve")
    instrText.text = "PAGE"

    fldChar2 = OxmlElement("w:fldChar")
    fldChar2.set(qn("w:fldCharType"), "end")

    run._r.append(fldChar1)
    run._r.append(instrText)
    run._r.append(fldChar2)


def add_toc_placeholder(document: Document) -> None:
    """Reuse application helper for TOC placeholder."""
    _add_toc_placeholder(document)


def add_title_page(document: Document, username: str, total_count: int) -> None:
    """Add title page with metadata."""
    title = document.add_heading("Recommendations Export", level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Metadata table
    table = document.add_table(rows=3, cols=2)
    table.style = "Light Grid Accent 1"

    table.rows[0].cells[0].text = "Generated By"
    table.rows[0].cells[1].text = username

    table.rows[1].cells[0].text = "Generated Date"
    now = datetime.now(timezone.utc)
    table.rows[1].cells[1].text = now.strftime("%Y-%m-%d %I:%M %p UTC")

    table.rows[2].cells[0].text = "Total Recommendations"
    table.rows[2].cells[1].text = str(total_count)

    # Format table
    for row in table.rows:
        row.cells[0].paragraphs[0].runs[0].bold = True
        for cell in row.cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(9)

    document.add_page_break()


def add_recommendation_section(document: Document, recommendation: Recommendation) -> None:
    """Add a formatted recommendation section to the document."""
    from core.utilities.get_name_acronym import get_name_acronym

    # H1 Heading for recommendation name
    heading = document.add_heading(recommendation.name or "Untitled Recommendation", level=1)
    heading.runs[0].font.size = Pt(14)

    # Metadata table
    table = document.add_table(rows=0, cols=2)
    table.style = "Light Grid Accent 1"

    # Priority (with color coding)
    row = table.add_row()
    row.cells[0].text = "Priority"
    priority_cell = row.cells[1]
    priority_cell.text = recommendation.priority or "Not Set"

    # Color-code priority
    if recommendation.priority == RECOMMENDATION_PRIORITY_HIGH:
        for run in priority_cell.paragraphs[0].runs:
            run.font.color.rgb = RGBColor(220, 38, 38)  # Red
            run.bold = True
    elif recommendation.priority == RECOMMENDATION_PRIORITY_MEDIUM:
        for run in priority_cell.paragraphs[0].runs:
            run.font.color.rgb = RGBColor(234, 179, 8)  # Amber
    elif recommendation.priority == RECOMMENDATION_PRIORITY_LOW:
        for run in priority_cell.paragraphs[0].runs:
            run.font.color.rgb = RGBColor(34, 197, 94)  # Green

    # Status
    row = table.add_row()
    row.cells[0].text = "Status"
    row.cells[1].text = recommendation.status or "Not Set"

    # Dates
    if recommendation.date_recommended:
        row = table.add_row()
        row.cells[0].text = "Date Recommended"
        row.cells[1].text = recommendation.date_recommended.strftime("%Y-%m-%d")

    if recommendation.date_target_completion:
        row = table.add_row()
        row.cells[0].text = "Target Completion"
        row.cells[1].text = recommendation.date_target_completion.strftime("%Y-%m-%d")

    if recommendation.date_completed:
        row = table.add_row()
        row.cells[0].text = "Date Completed"
        row.cells[1].text = recommendation.date_completed.strftime("%Y-%m-%d")

    # Recommended by
    if recommendation.person_recommended_by:
        row = table.add_row()
        row.cells[0].text = "Recommended By"
        person = recommendation.person_recommended_by
        row.cells[1].text = person.full_name_for_human if hasattr(person, "full_name_for_human") else str(person)

    # Related entities
    if recommendation.application:
        row = table.add_row()
        row.cells[0].text = "Related Application"
        row.cells[1].text = get_name_acronym(
            acronym=recommendation.application.acronym, name=recommendation.application.name
        )

    if recommendation.project:
        row = table.add_row()
        row.cells[0].text = "Related Project"
        row.cells[1].text = recommendation.project.name if hasattr(recommendation.project, "name") else str(recommendation.project)

    if recommendation.estimation:
        row = table.add_row()
        row.cells[0].text = "Related Estimation"
        row.cells[1].text = recommendation.estimation.name if hasattr(recommendation.estimation, "name") else str(recommendation.estimation)

    # Format table cells
    for row in table.rows:
        row.cells[0].paragraphs[0].runs[0].bold = True
        for cell in row.cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.size = Pt(9)

    # Add spacing
    document.add_paragraph()

    # Description section
    if recommendation.description:
        document.add_heading("Description", level=2)
        para = document.add_paragraph(recommendation.description)
        for run in para.runs:
            run.font.size = Pt(9)

    # Rationale section
    if recommendation.rationale:
        document.add_heading("Rationale", level=2)
        para = document.add_paragraph(recommendation.rationale)
        for run in para.runs:
            run.font.size = Pt(9)

    # Expected Benefits section
    if recommendation.benefits:
        document.add_heading("Expected Benefits", level=2)
        para = document.add_paragraph(recommendation.benefits)
        for run in para.runs:
            run.font.size = Pt(9)

    # Potential Risks section
    if recommendation.risks:
        document.add_heading("Potential Risks", level=2)
        para = document.add_paragraph(recommendation.risks)
        for run in para.runs:
            run.font.size = Pt(9)

    # Additional Notes section
    if recommendation.comment:
        document.add_heading("Notes", level=2)
        para = document.add_paragraph(recommendation.comment)
        for run in para.runs:
            run.font.size = Pt(9)
